googled17825bc629bcc97.html
=> verify domain ownership

_includes/ga.html, _includes/head.html
=> Introducing: Google Analytics!

.travis.yml
Travis should phone ensemble about build status.
Don't bother building release and deploy branches, we've seen 'em.
=> tweak travis configuration

robots.txt
Configuring search console, linking to analytics account. This is causing robotic consternation.
=> remove robots.txt, getting in the way of GOOG setup

s3_website.yml
` /docs --> http://helm.readthedocs.org/en/latest/`
=> Add docs URL redirect

_includes/header.html, _sass/_helm.scss, javascripts/ui.js
The main page is currently served at `/coming_soon.html`.
=> Responsive Implementation of main page

_includes/header.html, _layouts/index.html
Now pointing to the new github URL!
=> chore(href) moving helm github links to github.com/helm

index.html
* Update contributor count
* Correct grammar
=> Edit homepage copy

docs/themes/helmdocs/static/src/js/custom/app_init.js, docs/themes/helmdocs/static/src/sass/docs-content.scss
Changes:
* add permalink on hover of titles (h1 to h6)
* remove scrollspy code, throwing console errors
* update the JS that applies an active state to the sidebar menu
--
The changes are [deployed to staging here](http://docs-helm-sh.staging.deis.com/) for review. Gif of the permalink icon hover effect:
--
Closes [#48](https://github.com/helm/helm-www/issues/48) and [#2633](https://github.com/kubernetes/helm/issues/2633) on kubernetes/helmFixes
=> Javascript Tidy Ups

docs/config.toml
See https://github.com/kubernetes/helm/issues/3090
=> Fix wrong reference to listo in sidebar

docs/config.toml, docs/gulpfile.js
relies on https://github.com/kubernetes/helm/pull/3094
=> add RBAC docs

docs/config.toml, docs/gulpfile.js
Updates the sidebar links, gulp task that puts creates the `/using_helm` sub section
=> Add security doc

helm.sh/assets/scss/_mixins.scss, helm.sh/assets/scss/app.scss
Removes the `"` character that breaks the site when hosted from blob storage.
=> remove the quote mixin

brigade.js
This provides a brigade build for a CI pipeline.
=> [WIP] feat(*): Add brigade.js for builds

docs.helm.sh/config.toml
relies on https://github.com/kubernetes/helm/pull/3836
=> rename TPR to CRD

docs.helm.sh/config.toml, docs.helm.sh/gulpfile.js
Indexes this page in the same manner as the other `using_helm`pages, so it's more prominent in the site sidebar menu.
=> [docs] add the tiller_ss doc to the site menu

helm.sh/_posts/2018-05-31-cncf.md
Adds the [announcement post](https://user-images.githubusercontent.com/686194/40826464-861dc766-652f-11e8-8e32-75961548eaf7.png) to the blog.
=> add cncf post

helm.sh/README.md
Updates the info in the `helm.sh/Readme.md` around the site hosting and deployment.
More to follow
=> [helm.sh] updated outdated info in helm.sh readme

helm.sh/README.md
We are going to start adding blog posts so some directions seemed relevant. Does this work? Does the image location work?
=> Adding directions on adding a blog post

brigade.js
Adding a `push` to brigade.js, so the site will auto-build and deploy when changes are merged on GitHub.
=> update brigade.js for github push

README.md, docs.helm.sh/README.md, helm.sh/README.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> GitHub org links updated in markdown files.

helm.sh/_posts/2018-07-23-bring-helm-home.md
While I would have loved to have written this, I didn't. IIRC, @technosophos did.
Tweaked a few other things for accuracy.
=> Correcting the bringing helm home post and prefixing the url

docs.helm.sh/themes/helmdocs/layouts/index.html, helm.sh/index.html
I noticed a "to" that is probably supposed to be a "for", and fixed a little punctuation while I was sending a PR anyhow.
=> Fixing typos

helm.sh/_posts/2018-08-27-helm-switch-dco.md
**THIS SHOULD NOT BE MERGED UNTIL THE DCO SWITCH HAPPENS.**
The person who switches the automation should merge this post so it goes live.
cc @caniszczyk @technosophos
=> Adding blog post on DCO switch

helm.sh/_posts/2018-09-07-new-gov-and-elections.md
This should not be posted until the docs merge has been completed and the links are updated.
=> Adding blog post on new gov and elections

helm.sh/_posts/2019-01-14-helm-security-notice.md
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
=> Add missing hyphen

helm.sh/_posts/2019-01-14-helm-security-notice.md
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
=> Use correct hyphen

helm.sh/_posts/2019-01-14-chartmuseum-security-notice.md
Noticed a very small typo, might want to get it fixed :).
=> Typo in blog

content/blog/2018-06-01-cncf.md, content/blog/2018-07-24-helm-emeritus-rimus.md, themes/helm/layouts/docs/list.html, themes/helm/static/src/sass/docs-home.scss
GA gathers basic metrics on the site, but hasn't included across the docs pages. This includes it across all pages.
=> [docs] add analytics

content/blog/2019-04-22-helm-3-preview-pt1.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
=> Added in link to next blog post series

themes/helm/layouts/blog/list.html, themes/helm/layouts/blog/single.html, themes/helm/layouts/docs/list.html, themes/helm/layouts/index.html, themes/helm/layouts/partials/banner.html, themes/helm/layouts/partials/topbar.html, themes/helm/static/src/sass/docs-home.scss, themes/helm/static/src/sass/docs-responsive.scss, themes/helm/static/src/sass/docs-sidebar.scss, themes/helm/static/src/sass/docs-topbar.scss, themes/helm/static/src/sass/helm-home.scss
Adds a sticky banner to the site which states:
* highlights the coming of Helm 3
* states what version of Helm you are currently viewing info on
* links to the other version
=> [v3] add a sticky banner for helm 2 and helm info

content/blog/2019-06-10-get-helm-sh.md
=> [HOLD] add blog post on get.helm.sh

config.toml, gulpfile.js
re: https://github.com/helm/helm/pull/5754
=> Helm 3: add registry docs to sidebar

gulpfile.js
=> [#229] rewrite fix for chart development url

content/docs/community/release_checklist.md
The latest changes from from the current 2.x docs and include:
- PGP signing
- The keys file
- The changelog template
- Directions to bring the version from the release branch to master
=> Updated the release docs to bring in latest changes

content/docs/faq.md
=> docs(faq): 3-way merge patch, XDG, storage driver

content/docs/faq.md
addresses https://github.com/helm/helm/issues/5907
=> docs(faq): mark OCI as experimental, add note about apiVersion bump

content/docs/topics/registries.md
Updates related to recent changes in helm/helm dev-v3
=>  Pre-beta registry doc updates

content/docs/topics/registries.md
=> registries typo

content/docs/topics/charts.md
Depends on https://github.com/helm/helm/pull/6332
=> feat: Add documentation about the new crds directory.

content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Signed-off-by: rimas <rmocius@gmail.com>
=> Post: update migrate-from-helm-v2-to-helm-v3 with clean up feature

content/docs/topics/charts.md
=> docs(topics): add details about the LICENSE file

content/docs/intro/v2_v3_migration.md
Signed-off-by: rimas <rmocius@gmail.com>
=> Update v2_v3_migration doc with link to migration blog post

config.toml, themes/helm/layouts/partials/banner.html
Perhaps we want to list current beta versions on the website?
=> Updating versions mentioned on website

content/docs/intro/rbac.md
closes https://github.com/helm/helm/issues/5613
=> feat(rbac): add Role-based Access Control documentation

README.md, content/code/helm-v2.md, content/code/helm.md, gulpfile.js
=> fix: update branch to dev-v2

content/code/helm.md, content/docs/topics/charts.md
=> fix: update dev-v3 to master branch

content/blog/2019-10-22-helm-2150-released.md
DO NOT MERGE until October 22, 2019 (tomorrow)
=> feat(blog): Helm 2.15.0 Released

content/docs/glossary.md, content/docs/intro/kubernetes_distros.md
There are a few formatting/grammatical fixes and I removed Container Linux
because it technically part of Red Hat and OpenShift related work (please
correct me if I am wrong).
I also updated a git conflict I forgot to save and it was accidentally
committed
=> Updates Kubernetes distros to match v2

content/docs/topics/chart_best_practices/custom_resource_definitions.md
This also contains some basic explainations for the design decisions
around the Helm 3 CRD support. I wanted to add a single source to explain
to people in the future about why specific behaviors were decided upon
=> Updates CRD documentation with the latest instructions for v3

content/docs/howto/chart_repository_sync_example.md, content/docs/intro/quickstart.md, content/docs/intro/using_helm.md, content/docs/topics/chart_repository.md, content/docs/topics/chart_template_guide/builtin_objects.md, content/docs/topics/chart_template_guide/subcharts_and_globals.md, content/docs/topics/charts.md, content/docs/topics/plugins.md, content/docs/topics/registries.md
See https://gohugo.io/content-management/cross-references/
closes #326 
=> fix(docs): fix hyperlink lookups

content/code/chartmuseum.md, content/code/helm-v2.md, content/code/helm-v3.md
This will allow `go get helm.sh/helm` to continue to work after the migration.
=> chore(code): parity between code URLs

content/blog/2018-12-11-helm-hub.md, content/docs/community/developers.md, content/docs/community/history.md, content/docs/community/related.md, content/docs/community/release_checklist.md, content/docs/intro/getting_started.md, content/docs/intro/using_helm.md, content/docs/topics/chart_best_practices/conventions.md, content/docs/topics/chart_template_guide/control_structures.md, content/docs/topics/chart_template_guide/yaml_techniques.md, content/docs/topics/charts.md, content/docs/topics/plugins.md, content/docs/topics/provenance.md
=> fix(docs): use HTTPS everywhere

content/docs/community/history.md
=> Update the Helm history and remove unnecessary content

content/docs/topics/provenance.md
Update the documentation on signing/verifying to reflect the state of Helm 3.0.0
=> docs: update the provenance documentation for Helm 3

content/docs/community/developers.md
Updated several minor things that have changed since Helm 2.
=> docs: update documentation on building Helm

content/docs/community/related.md
=> fix URLs for adding new related links

content/docs/howto/charts_tips_and_tricks.md
=> fix: update formatting and content of tips and tricks

content/docs/community/release_checklist.md, content/docs/faq.md, content/docs/intro/install.md
see https://github.com/helm/helm/pull/6949
=> fix(install): update links to get-helm-3 script

content/docs/topics/chart_best_practices/conventions.md
=> fix: update best practices

content/docs/topics/chart_best_practices/templates.md
Fixed minor formatting issues.
=> fix: fixed formatting in templates.md

content/docs/topics/chart_best_practices/values.md
=> fix: fixed formatting of YAML samples

content/docs/topics/chart_template_guide/accessing_files.md
=> fix: minor fixes to the accessing-files.md document

content/docs/topics/chart_template_guide/debugging.md
=> fix: update debugging doc for helm 3

content/docs/topics/chart_template_guide/functions_and_pipelines.md
=> fix: fixed formatting in functions and pipelines docs

content/docs/intro/using_helm.md
=> Update the using-helm doc to v3

content/docs/topics/chart_template_guide/builtin_objects.md
=> fix: Updated builtin objects for Helm 3

content/docs/topics/charts_hooks.md
=> update hooks for Helm 3

content/docs/topics/charts.md, content/docs/topics/kubernetes_distros.md, content/docs/topics/plugins.md
=> fix: fix misc formatting issues

content/blog/2019-11-13-helm-3-released.md
=> feat(blog): Helm 3.0.0 has been released!

content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Signed-off-by: rimas <rmocius@gmail.com>
=> Update migration 2 to 3 post with latest plugin changes

content/docs/intro/using_helm.md
Migrating commands in documents to v3 format.
=> Replace helm inspect with helm inspect

content/docs/intro/install.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> Use the v3 tarball by default

content/docs/topics/v2_v3_migration.md
=> Remove repeated word 'to' in v2_v3_migration.md

content/docs/topics/v2_v3_migration.md
- ref: the Note section from
https://github.com/helm/helm-2to3#readme-before-migration
=> v2_v3_migration.md: explicitly mention the Helm version in note

themes/helm/assets/js/app.js, themes/helm/assets/sass/docs-sidebar.scss, themes/helm/layouts/partials/sidebar.html
As per title. Closes issue #377.
=> [docs] reinstate the site search for v3 docs

content/docs/topics/v2_v3_migration.md
=> Fix some syntax inconsistency

themes/helm/assets/sass/helm-home.scss
=> Fix Issue #418

OWNERS
Pushing this PR after discussion on slack with @bacongobbler
=> Add Martin Hickey as core maintainer

content/docs/intro/install.md
Small change to the install docs, just updated the file extension to match what was in the github release downloads
Thanks!
=> Changed  download file extension to .tar.gz to match the download files

content/docs/topics/chart_repository.md
Based on this PR: https://github.com/helm/helm/pull/7254
Signed-off-by: Matthias Riegler <me@xvzf.tech>
=> Added docs for adding repos with --insecure-skip-tls-verify

content/docs/intro/install.md
This is my first PR to helm. I made it after this discussion: https://github.com/helm/helm/issues/7215#issuecomment-565386482
=> Add hint to add the stable repo

content/docs/faq.md
I was bitten by not fully understanding the implications of the namespace changes in Helm 3. Looking at the issues list helm/helm#7146, helm/helm#7081, helm/helm#6971, helm/helm#6441, helm/helm#6159, this is a common mistake, hence suggesting an addition to the FAQ.
=> Reduce common confusion around namespace changes in v3

content/docs/community/related.md
This PR adds info about `helm-s3` plugin and `helm-schema-gen` plugin
Fixes #450 
and
Fixes #451
=> Add plugins info for helm-s3 and helm-schema-gen

content/docs/chart_template_guide/getting_started.md
=> Fix link to Chart Template Guide

content/docs/chart_template_guide/getting_started.md
Signed-off-by: Sreeram Padmanabhan <sreeram.padmanabhan@deliveryhero.at>
Fixes #408
=> docs: fixes getting started docs helm install command

content/docs/chart_template_guide/builtin_objects.md
=> fix the capabilities object key name for kubernetes version

themes/helm/layouts/index.html
=> Fixing the v2 docs link on the v2 site

content/docs/chart_template_guide/getting_started.md
These fixes make the sequence working  
```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
=> Getting started essential fixes

content/docs/intro/using_helm.md
=> --generate-name is given to successfully install chart

content/docs/community/release_checklist.md
Release checklist was updated with some fixes in v2 stream. This commit pulls over those fixes.
=> fix(community): Port fixes from v2 release checklist

content/docs/howto/charts_tips_and_tricks.md
=> Restoring docs on tpl template function

content/en/docs/topics/chart_repository.md
Signed-off-by: Mans Singh <mans2singh@yahoo.com>
=> Removed duplicate title

content/en/docs/topics/chart_best_practices/conventions.md, content/en/docs/topics/kubernetes_distros.md
Signed-off-by: Mans Singh <mans2singh@yahoo.com>
=> Corrected caps in description

content/en/docs/chart_template_guide/getting_started.md
Signed-off-by: Morgan Leroi <morgan.leroi@gmail.com>
=> docs: Missing parameter in command line

content/en/docs/topics/advanced.md
This section contains information on how to use post-render and some
basic examples of using the Go SDK
=> Adds advanced Helm techniques section

themes/helm/assets/sass/helm-home.scss
=> Align menu icons hover effect on center

content/en/docs/chart_template_guide/named_templates.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
same problem again , this command is old , i fixed it by writing that command with the new version of helm.
=> helm2 command changed as helm3 versioned

package.json, yarn.lock
I've been seeing some npm deprecation warnings in the CI output so I thought I'd do some due diligence and update the npm packages. This PR should have no effect beyond eliminating those warnings.
=> Update JS packages

i18n/en.toml
Follow up to #346, this fixes a typo
=> [v3 theme] fix events typo

themes/helm/layouts/partials/sidebar.html
Signed-off-by: lemonli <liwenjun0323@gmail.com>
fix sidebar `Contribute to Docs` link
fix #530
=> fix sidebar contribution link

content/en/docs/chart_template_guide/getting_started.md
=> Fixing broken link to chart template guide

content/en/docs/topics/library_charts.md
=> feat(topic): Improve library charts documentation

content/en/docs/helm/helm_install.md
Signed-off-by: Jay Rajput <jayrajput@gmail.com>
=> Added new line to fix formatting.

content/en/blog/2020-04-02-covid-19-extending-helm-v2-bug-fixes.md
@mattfarina and I wrote a blog post as an action item from the 2020-04-02 Helm community meeting.
=> Adding new blog post

content/en/docs/chart_template_guide/control_structures.md
Correcting a typo to make it readable
=> Correct a typo

content/en/docs/topics/advanced.md
=> feat(topics/advanced): Add the storage backend section

i18n/ko.toml
=> Convert get started to Korean

content/en/docs/faq/_index.md
Replaces #549
Corrects the `kubectl` command.
=> Fixing kubectl command

i18n/ko.toml
=> translation of copy

i18n/ko.toml
=> translation

i18n/ko.toml
=> TranslationKor1

themes/helm/assets/sass/docs-content.scss, themes/helm/assets/sass/docs-sidebar.scss
Resolves the css glitch that was affecting the search box on docs pages.
Closes #543.
=> [#543] fix search box cropping bug

content/en/docs/topics/kubernetes_distros.md
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
=> Fix the IKS Helm link

content/en/docs/topics/charts.md
Refactor the chart type section to improve explanation of library chart.
=> fix(charts): Update chart type section for better clarity

content/en/docs/intro/using_helm.md
=> en] uninstall or uninstall

config.toml
Signed-off-by: flynnduism <dev@ronan.design>
=> chore(docs): bump stable version to 3.2

content/ko/docs/intro/install.md
Translate intro/install.md in Korean
=> Translate intro/install.md in Korean

content/ko/docs/intro/quickstart.md
=> Translate /docs/quickstart/ in Korean

themes/helm/layouts/partials/footer-links.html, themes/helm/layouts/partials/footer-social.html, themes/helm/layouts/partials/nav-fixed.html, themes/helm/layouts/partials/nav.html
Hi, @flynnduism - can you check to see if it's okay to switch to https for these links? Thanks.
=> Convert helm.sh links for theme into internal links

content/en/docs/faq/_index.md
In reviewing https://github.com/helm/helm-www/issues/385, I have reworded the FAQ based on @bacongobbler and @mattfarina's comments. Review/edits as desired would be good.
=> Adding to the FAQ around Secrets vs ConfigMaps

content/en/docs/topics/kubernetes_distros.md
In reviewing https://github.com/helm/helm-www/issues/433, I think this could be a reasonable revision of that page. (The page does not have every link or update that would be possible, but this clarification at the top should help with any ambiguity.) Opinions and/or edits from @bacongobbler and @mattfarina would be helpful, as they commented on the original issue. Thanks!
=> Adding clarification about distros that work

content/ko/docs/intro/install.md
[language/ko] docs/intro/install.md minor edit
=> [language/ko] docs/intro/install.md minor edit

content/en/blog/2020-04-30-celebrating-helms-cncf-graduation.md
Link to CNCF post for graduation.
=> Add grad link

i18n/ko.toml
=> Review implemented

config.toml
Latest release for Helm 3 is 3.2.1
=> Update doc version to release 3.2.1

content/en/docs/chart_template_guide/accessing_files.md
Solution found via:
* https://github.com/helm/helm/issues/3403#issuecomment-377119404
Thanks @nelson-onyibe
fix helm/helm#3403
=> Fix examples how to use .Files.Glob

content/en/docs/faq/_index.md
The FAQ was correct for the initial release of Helm 3.  Updating to current capabilities.
Signed-off-by: Ken Sipe <kensipe@gmail.com>
=> FAQ Update for Create Namespace

config.toml
This PR update Helm versions in the v2 website navigation.
=> update helm versions in v2 website navbar

content/ko/docs/faq/_index.md
[translation/ko] docs/faq/_index.md
=> [translation/ko] docs/faq/_index.md

content/ko/docs/intro/_index.md
[translation/ko] docs/intro/_index.md
=> [translation/ko] docs/intro/_index.md

i18n/ko.toml
=> [translation/ko] i18n/ko.toml

content/en/docs/topics/kubernetes_apis.md
Doc: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest
=> Add ConfigMap backend details to steps for updating a release manifest

content/ko/docs/chart_best_practices/custom_resource_definitions.md
[translation/ko] docs/chart_best_practices/custom_resource_definitions.md
I want this reviewed now. Thanks.
=> [translation/ko] docs/chart_best_practices/custom_resource_definitions.md

content/ko/docs/chart_best_practices/dependencies.md, content/ko/docs/chart_best_practices/labels.md, content/ko/docs/chart_best_practices/pods.md, content/ko/docs/chart_best_practices/rbac.md, content/ko/docs/chart_best_practices/templates.md, content/ko/docs/chart_best_practices/values.md
[translation/ko] docs/chart_best_practices/some_files.md (partial)
I want this reviewed now. Thanks.
=> [translation/ko] docs/chart_best_practices/some_files.md 

i18n/en.toml, themes/helm/assets/sass/docs-topbar.scss, themes/helm/assets/sass/helm-home.scss, themes/helm/layouts/partials/banner.html
Updates the sticky banner at the top of the website with an racism message.
> Racism is unacceptable, is incompatible with the Helm project goals, and has no place in our open source community. #BlackLivesMatter
=> Community banner update

content/en/docs/helm/helm_upgrade.md
This should mean it is included in the site contents in the sidebar.
=> Add title to helm upgrade docs.

content/en/docs/community/history.md
innaugural → inaugural (community history)
=> innaugural → inaugural (community history)

content/en/docs/topics/version_skew.md
closes https://github.com/helm/helm/issues/6981
=> feat(topics): Helm Version Support Policy

config.toml
The versions listed as current on the website (in the docs) need to be bumped.
=> Updating current versions for website

content/en/docs/intro/using_helm.md
=> update `helm install` & `helm status` output

content/en/docs/chart_best_practices/custom_resource_definitions.md, content/en/docs/chart_best_practices/dependencies.md, content/en/docs/chart_best_practices/labels.md, content/en/docs/chart_best_practices/rbac.md, content/en/docs/chart_best_practices/values.md, content/en/docs/chart_template_guide/subcharts_and_globals.md, content/en/docs/chart_template_guide/values_files.md, content/en/docs/chart_template_guide/variables.md, content/en/docs/chart_template_guide/wrapping_up.md, content/en/docs/howto/chart_repository_sync_example.md, content/en/docs/howto/charts_tips_and_tricks.md, content/en/docs/intro/install.md, content/en/docs/intro/using_helm.md, content/en/docs/topics/advanced.md, content/en/docs/topics/charts.md, content/en/docs/topics/kubernetes_distros.md, content/en/docs/topics/plugins.md, content/en/docs/topics/rbac.md, content/en/docs/topics/v2_v3_migration.md
Signed-off-by: Bagrat Lazaryan <bagratte@live.com>
=> Proofread documentation

content/ko/docs/faq/_index.md
[translation/ko] docs/faq/_index.md #2
I want this reviewed now. Thanks.
=> [translation/ko] docs/faq/_index.md (partial)

content/ko/docs/community/history.md
[translation/ko] docs/community/history.md
=> [translation/ko] docs/community/history.md

i18n/en.toml, i18n/ko.toml, i18n/zh.toml, themes/helm/layouts/404.html, themes/helm/layouts/index.html, themes/helm/layouts/partials/footer-social.html, themes/helm/layouts/partials/footer.html
These PRs corrects a handful of http://* URLs.
=> Enforce https in URLs

config.toml
Let's keep the website updated.
=> 3.2.4 released

content/ko/docs/chart_best_practices/labels.md
[ko] chart_best_practices/labels.md (partial)
=> [ko] chart_best_practices/labels.md (partial)

content/en/docs/chart_template_guide/accessing_files.md, content/en/docs/chart_template_guide/control_structures.md, content/en/docs/chart_template_guide/function_list.md, content/en/docs/chart_template_guide/named_templates.md, content/en/docs/chart_template_guide/variables.md
This includes documentation of most of the template functions
available within Helm templates.
=> Adding documentation on template functions

content/ko/docs/chart_best_practices/custom_resource_definitions.md
[ko] chart_best_practices/custom_resource_definitions.md (partial)
바로 검토 부탁드립니다. 감사합니다.
I want this reviewed now. Thank you.
=> [ko] chart_best_practices/custom_resource_definitions.md

config.toml
[ko] helm-www/config.toml (languages.ko.)
=> [ko] helm-www/config.toml (languages.ko.)

i18n/zh.toml
Replace  zh. toml  with the latest en.toml
Signed-off-by: arunfung <arunfung@gmail.com>
=> Replace  zh. toml  with the latest en.toml

themes/helm/layouts/index.html
Signed-off-by: arun fung <arunfung@gmail.com>
=> fix community_slack_join display

i18n/ko.toml
=> [ko] ko.toml (partial)

content/ko/docs/chart_best_practices/pods.md
[ko] chart_best_practices/pods
=> [ko] chart_best_practices/pods

content/en/docs/community/related.md
Added the Terraform Helm provider to content/en/docs/community/related.md
=> Added the Terraform Helm provider to Additional Tools

content/en/docs/topics/chart_tests.md, content/en/docs/topics/charts.md
I looked into https://github.com/helm/helm-www/pull/504 and found that instead of a simple typo, we had a rather confusing message. I have attempted to clarify so that someone who is new to chart testing has a workable model they can follow. 
=> Clarify chart testing

netlify.toml
=> bump hugo to 0.73.0

content/en/docs/chart_template_guide/control_structures.md
This section of text explains that $ can be used but does not
explain what it is. Further explaining on the language.
=> Explaining what $ is

content/en/docs/topics/charts_hooks.md
See helm/helm#7432
Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>
=> refine info on install order of hooks.

content/en/docs/topics/advanced.md
Add the storage backend section
Merge when:
=> Add the SQL storage backend doc

content/en/docs/chart_best_practices/pods.md, content/ko/docs/chart_best_practices/pods.md
The docs were missing `image:`.
=> Specify full nested yaml property in imagePullPolicy of 'Pods and PodTemplates' best practices

content/en/docs/topics/chart_tests.md
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
=> show helm3 test hook example, not helm2

content/en/docs/community/history.md
I noticed a translation PR which was translating this doc, and I saw that we need to add info about graduation.
=> Updating for CNCF graduation

content/en/blog/2020-08-13-helm-v2-deprecation-timeline.md
=> Adding blog post

content/en/docs/community/related.md
Related to https://github.com/helm/helm/issues/8609
=> Add link to avionix

content/en/docs/intro/using_helm.md
When reading the intro from the beginning, values.yaml is mentioned before explaining what Value Files are, so I thought a link to that doc from there would be helpful. 
Also, I couldn't find the mentioned next chapter, I am assuming is for v3 and not available yet, so just noted that so it doesn't look incorrect.
=> Using Helm doc: Link to info on Value Files and note missing next chapter

content/en/docs/community/release_checklist.md
Adding a few clarifications to the release notes based on discussion with @mattfarina.
=> Adding release notes details

content/ja/docs/glossary/_index.md, content/ja/docs/topics/advanced.md, i18n/ja.toml
Signed-off-by: Yuuki Ebihara <yuuki.ebihara813@gmail.com>
=> glossary translation

content/en/docs/topics/chart_tests.md
Adding clarification about backward compatibility as discussed in https://github.com/helm/helm/issues/7856.
=> Clarify test success

content/zh/docs/chart_best_practices/_index.md, content/zh/docs/chart_template_guide/_index.md, content/zh/docs/intro/_index.md
Per https://github.com/helm/helm-www/issues/775 these are added in error.
=> Removing incorrect aliases

content/ja/docs/glossary/_index.md
Translated the rest of the glossary.
=> Translate the rest of it.

config.toml, content/en/docs/community/release_checklist.md
Update Helm v3 docs version and add some missing info discovered during the 3.3.1 release.
=> Update release checklist, 3.3.1 improvements

content/zh/docs/faq/_index.md, content/zh/docs/glossary/_index.md
=> Add Chinese docs for faq and glossay

content/zh/docs/intro/install.md, content/zh/docs/intro/quickstart.md, content/zh/docs/intro/using_helm.md
Hi docs team,
I do some translate work for chinese docs, for this PR I transalte the **quickstart** page.
Add the install page and using helm page was just make it not break compile.
If any issue for this PR, give me feedback please.
@flynnduism @bridgetkromhout
=> Add chinese translation for quickstart page

content/en/docs/chart_template_guide/named_templates.md
I wanted to capture the clarification in https://github.com/helm/helm/issues/7961#issuecomment-620143810 in the docs. Input from @technosophos and others welcome as to whether there is a better way or place to explain this.
=> Clarify how define produces output

content/en/docs/faq/_index.md
=> add FAQ about the mdns_debug file

content/ko/docs/chart_template_guide/debugging.md
Signed-off-by: bluefriday <bluefriday86@gmail.com>
Translate docs/chart_template_guide/debugging.md in Korean
- https://helm.sh/ko/docs/chart_template_guide/debugging/
=> Translate docs/chart_template_guide/debugging.md in Korean

content/en/docs/faq/_index.md
Adding to the v3 FAQ based on @bacongobbler's answer for https://github.com/helm/helm/issues/7951. 
=> Adding clarification about APIVersion

config.toml
=> version bump

content/ko/docs/chart_template_guide/getting_started.md
Translate chart_template_guide/getting_started.md into Korean
- https://helm.sh/docs/chart_template_guide/getting_started/
Signed-off-by: markruler <csu0414@gmail.com>
=> Translate chart_template_guide/getting_started.md into Korean

config.toml
=> bump to v2.16.12/v3.3.3

content/ko/docs/community/localization.md
Translate community/localization.md into Korean
- https://helm.sh/docs/community/localization/
Signed-off-by: markruler <csu0414@gmail.com>
=> Translate community/localization.md into Korean

content/en/docs/faq/_index.md
=> [en] missing parentheses

content/en/docs/faq/_index.md
ref: https://github.com/helm/helm/pull/8067
=> Add Kubernetes client logging to FAQ

content/en/docs/topics/v2_v3_migration.md
While reviewing translation, I noticed some places that could be confusing or have multiple meanings.
=> Clarifications in the v2 to v3 migration doc

content/ja/docs/howto/charts_tips_and_tricks.md
Signed-off-by: Yuuki Ebihara <yuuki.ebihara813@gmail.com>
=> Translate 'charts_tips_and_tricks' into Japanese.

content/ja/docs/howto/charts_tips_and_tricks.md
Fixing small issue from https://github.com/helm/helm-www/pull/878
=> Removing incorrect alias

content/ko/docs/topics/registries.md
Translate topics/registries.md into Korean
- https://helm.sh/docs/topics/registries/
Signed-off-by: markruler <csu0414@gmail.com>
=> Translate topics/registries.md into Korean

i18n/ko.toml
according to the change of the original banner
Signed-off-by: June Yi <gochist@gmail.com>
=> Update the Korean banner

content/en/docs/howto/charts_tips_and_tricks.md
Clarification for https://github.com/helm/helm/issues/6456.
=> Clarifying random strings between templates

content/en/docs/helm/helm_completion_bash.md, content/en/docs/helm/helm_completion_zsh.md
I had an error creep in that apparently I didn't correct in all cases. Noticed this because it was appearing in translations.
=> Fixing paths

README-ko.md
Closes #854 
Signed-off-by: markruler <csu0414@gmail.com>
=> Translate README.md into Korean

config.toml, content/en/blog/2020-10-26-new-location-stable-incubator-charts.md
This includes two things...
1. A blog post on 3.4 and 2.17 that talks about the charts move
2. param updates for the new versions
=> Release v3.4 and v2.17 post and config

content/en/docs/topics/charts_hooks.md
=> [en] missing 'request'

content/en/blog/2020-10-30-charts-repo-deprecation.md
Slight updates to https://github.com/helm/helm-www/pull/916.
=> Blog addition amendments

content/ja/docs/community/localization.md
I translated `community/localization.md` to Japanese.
=> [ja] Translate community/localization in Japanese

content/en/blog/2020-10-26-new-location-stable-incubator-charts.md
Signed-off-by: Gabrielle Madden <49839049+gabriellemadden@users.noreply.github.com>
=> Specify the old locations being referred to

README.md
After I needed to consult @flynnduism to figure out how to accomplish https://github.com/helm/helm-www/pull/930, he suggested I note this for the next person who needs to do this.
=> Clarify how to update sidebar.

config.toml, gulpfile.js
Addition for https://github.com/helm/helm-www/pull/925
Co-authored-by: Martin Hickey <martin.hickey@ie.ibm.com>
=> Adding deprecated APIs link to sidebar

content/en/blog/2020-11-13-helm-2-becomes-unsupported.md
=> add last blog post on Helm 2 deprecation

content/ja/docs/faq/_index.md
Hello!🙂 I've updated the Japanese translation of the FAQ page. This PR translates 8 sections on the page.
Related issue: #843.
=> Translate several sections in faq page into Japanese

content/en/docs/intro/install.md
=> Add FreeBSD package installation instructions

content/ko/docs/howto/chart_repository_sync_example.md
Conflicted files in the my previous PR, So I open a new PR. 
I ask for your understanding. 
Reviews already are reflected. 
my previous PR  : https://github.com/helm/helm-www/pull/913
Signed-off-by: sunminjeon <sunmin.jeon@samsung.com>
[ko] Translate chart_repository_sync_example. in Korean
=> [ko] Translate chart_repository_sync_example in Korean

content/zh/docs/helm/helm.md, content/zh/docs/helm/helm_delete.md, content/zh/docs/helm/helm_get.md, content/zh/docs/helm/helm_install.md, content/zh/docs/helm/helm_lint.md, content/zh/docs/helm/helm_package.md, content/zh/docs/helm/helm_plugin.md, content/zh/docs/helm/helm_plugin_install.md, content/zh/docs/helm/helm_plugin_list.md, content/zh/docs/helm/helm_plugin_uninstall.md, content/zh/docs/helm/helm_plugin_update.md, content/zh/docs/helm/helm_pull.md, content/zh/docs/helm/helm_repo.md, content/zh/docs/helm/helm_repo_add.md, content/zh/docs/helm/helm_repo_index.md, content/zh/docs/helm/helm_repo_list.md, content/zh/docs/helm/helm_repo_remove.md, content/zh/docs/helm/helm_repo_update.md, content/zh/docs/helm/helm_rollback.md, content/zh/docs/helm/helm_search.md, content/zh/docs/helm/helm_search_hub.md, content/zh/docs/helm/helm_show.md, content/zh/docs/helm/helm_show_all.md, content/zh/docs/helm/helm_show_chart.md, content/zh/docs/helm/helm_show_readme.md, content/zh/docs/helm/helm_show_values.md, content/zh/docs/helm/helm_template.md, content/zh/docs/helm/helm_test.md, content/zh/docs/intro/install.md, content/zh/docs/topics/registries.md
=> [zh] Update helm title for Chinese docs

content/ko/docs/helm/helm.md
Signed-off-by: bluefriday <bluefriday86@gmail.com>
[ko] update 'helm command : helm' according to changed origin en docs
=> [ko] update 'helm command : helm' according to changed origin en docs

content/en/docs/topics/advanced.md
Fixes https://github.com/helm/helm-www/issues/1003
=> Note how secrets end up in the helm storage backend

content/en/docs/chart_template_guide/function_list.md
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> fix: change semver example

content/en/docs/intro/using_helm.md
=> use bitnami/wordpress as the example

content/en/docs/community/related.md
[Move2Kube](https://konveyor.io/move2kube/) helps users create helm charts for existing projects, and even parameterizes common variables. It supports source platforms which are not yet containerized, supports cloud foundry, docker compose and more. It can also support Kubernetes artifacts as source.
=> Add Move2Kube to additional tools

content/en/docs/chart_template_guide/function_list.md
http://masterminds.github.io/sprig/reflection.html#kind-functions
closes #1025
=> isKind -> kindIs

config.toml
Looks like I missed this with the last release.
=> Bumping version to 3.5.2

content/en/docs/topics/charts.md
- Fixed "aggregrated" into "aggregated"
- Added missed round bracket
=> Fix some typo

config.toml, content/fr/docs/_index.md, content/fr/docs/intro/_index.md, content/fr/docs/intro/install.md, content/fr/docs/intro/quickstart.md, content/fr/docs/intro/using_helm.md, i18n/fr.toml
Signed-off-by: Vincent Monnot <vincentmonnot@yahoo.fr>
=> French translation

config.toml
=> Updating version number

config.toml, content/es/docs/_index.md, content/es/docs/intro/_index.md, content/es/docs/intro/install.md, content/es/docs/intro/quickstart.md, content/es/docs/intro/using_helm.md, i18n/es.toml
=> Spanish translation

content/zh/docs/faq/_index.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
=> [zh] Fix typo

config.toml
Updating version listed as latest.
=> Updating for 3.5.4

i18n/fr.toml
Updated for other languages in https://github.com/helm/helm-www/pull/1054 - making this change for consistency.
=> Update to match all languages

content/es/docs/_index.md, content/es/docs/howto/_index.md, content/es/docs/howto/chart_repository_sync_example.md, content/es/docs/howto/charts_tips_and_tricks.md, i18n/es.toml
=> Translate docs/howto to Spanish

content/zh/docs/community/developers.md
=> [zh] Update Chinese docs

content/es/docs/_index.md, content/es/docs/howto/_index.md, content/es/docs/howto/chart_repository_sync_example.md, content/es/docs/topics/_index.md, content/es/docs/topics/charts.md
- Fix extra `)` from [PR](https://github.com/helm/helm-www/pull/1072)
- Translate Docs/Topics/Charts.
=> [es] Translate docs/topics/charts to Spanish

content/es/docs/topics/charts_hooks.md
- Translate docs/topics/charts_hooks.
=> [es] Translate docs/topics/charts_hooks to Spanish

content/es/docs/topics/chart_tests.md
- Translate docs/topics/charts_tests.
=> [es] Translate docs/topics/charts_tests to Spanish

content/en/docs/community/related.md
This PR adds a new plugin under plugins and other third party projects. Related to #1079
=> add new plugin

content/es/docs/_index.md, content/es/docs/howto/_index.md, content/es/docs/topics/charts.md, content/es/docs/topics/library_charts.md
- Translate docs/topics/library_charts.
=> [es] Translate docs/topics/library_charts to Spanish

content/zh/docs/howto/charts_tips_and_tricks.md
=> Update Chinese doc

content/es/docs/topics/provenance.md
- Translate docs/topics/provenance.
=> [es] Translate docs/topics/provenance to Spanish

content/zh/docs/community/related.md
=> [zh] Update Chinese doc

content/en/docs/howto/chart_releaser_action.md, content/en/docs/topics/chart_repository.md
Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>
=> Add documentation for Chart Releaser Action

content/en/docs/howto/chart_releaser_action.md
Making adjustment requested by @bacongobbler in https://github.com/helm/helm-www/pull/928#pullrequestreview-654621163.
=> Adjust weight for page

content/en/docs/chart_template_guide/function_list.md
(Most likely people have seen it in a different lang before C)
=> Capitalize C, and noted it's in other langs as well

content/zh/docs/chart_template_guide/function_list.md, content/zh/docs/community/related.md, content/zh/docs/howto/chart_releaser_action.md, content/zh/docs/topics/chart_repository.md
=> [zh] Add Chinese docs

content/en/docs/chart_template_guide/function_list.md
Just fixing various typos I noticed while reading. Thanks!
=> docs: fix various typos in function_list.md

content/zh/docs/intro/using_helm.md
`集群` is better than `群集`, especially in computer world.
=> docs: fix chinese expression

content/en/docs/intro/using_helm.md
Closes [#9726](https://github.com/helm/helm/issues/9726)
Signed-off-by: Anchal Agarwal <agarwalanchal72@gmail.com>
=> Added install order of resources

OWNERS
I checked with @thomastaylor312, and his wish is to be moved to emeritus in this repo just as he moved himself to emeritus in https://github.com/helm/helm/pull/9602.
=> Moving Taylor to emeritus

content/en/blog/2021-06-23-welcome-martin-hickey.md, content/en/blog/2021-06-24-welcome-martin-hickey.md
=> added new blog post for Martin

content/en/docs/topics/chart_repository.md
Signed-off-by: Ciara Carey <ccarey@cloudsmith.io>
=> Adjust docs to add Cloudsmith as a potential chart repository

content/en/docs/topics/library_charts.md
=> Helm Helper Chart is archived

content/en/docs/topics/provenance.md
=> convert pubring to legacy gpg format

content/zh/docs/chart_best_practices/conventions.md
Signed-off-by: yxxhero <aiopsclub@163.com>
=> [zh] fix some chinese typo

content/ko/docs/howto/charts_tips_and_tricks.md
Signed-off-by: nuguni <nuguni@kakao.com>
=> Translate_KR:Quote Strings ~

config.toml, content/pt/docs/_index.md, content/pt/docs/community/_index.md, content/pt/docs/howto/_index.md, content/pt/docs/intro/_index.md, content/pt/docs/topics/_index.md, i18n/pt.toml
The localization contribution minimum requirements are satisfied within this PR.
Tried as much to bring Portuguese IT industry terms as did @nikfot in [Add Greek Language
](https://github.com/helm/helm-www/pull/1095#issuecomment-835142054) for Greek.
=> [pt] Adding Portuguese Language 

content/pt/docs/intro/install.md, i18n/pt.toml
=> [pt] Adding installation page

content/en/docs/chart_template_guide/builtin_objects.md
PR to add the property HelmVersion to the information about Capabilities object
=> Add details about Capabilities.HelmVersion

content/en/docs/topics/charts.md
Closes issue #1157 
Signed-off-by: Alex Petrov <alex.petrov.vt@gmail.com>
=> Fix error about dependency chart format

content/pt/docs/intro/quickstart.md
=> [pt] Adding Portuguese Quickstart Guide

content/pt/docs/glossary/_index.md, content/pt/docs/intro/install.md, content/pt/docs/intro/quickstart.md
=> [pt] Adding Portuguese Glossary

content/pt/docs/helm/_index.md, content/pt/docs/helm/helm.md, content/pt/docs/helm/helm_create.md
=> [pt] Adding Helm Commands (index + create)

content/en/docs/community/related.md
- Sort related projects alphabetically
- Fix YAML linting along the way
- Add Flux to Tools section
=> Add Flux to Helm docs under Community > Related Projects > Tools

content/pt/docs/helm/helm.md, content/pt/docs/helm/helm_completion.md, content/pt/docs/helm/helm_completion_bash.md, content/pt/docs/helm/helm_completion_fish.md, content/pt/docs/helm/helm_completion_zsh.md, content/pt/docs/helm/helm_create.md, content/pt/docs/helm/helm_get.md, content/pt/docs/helm/helm_get_all.md, content/pt/docs/helm/helm_get_hooks.md, content/pt/docs/helm/helm_get_manifest.md, content/pt/docs/helm/helm_get_notes.md, content/pt/docs/helm/helm_get_values.md, content/pt/docs/helm/helm_install.md
=> [pt] Adding Helm Get Commands

content/pt/docs/helm/helm.md
=> [pt] Updating references to Portuguese commands

content/en/docs/helm/helm_install.md, content/en/docs/helm/helm_upgrade.md
=> Adds CRDs Caveats in Helm Install and Upgrade Commands

content/en/docs/topics/charts.md
=> Revert "Make `version` optional for dependencies"

content/zh/docs/topics/chart_repository.md
=> [#1192] [zh] fix broken link in chart_repository page

config.toml, content/en/docs/topics/version_skew.md
Date for Helm 3.8.0 is tentative - will bring up in this week's community call
=> helm 3.7.0

content/ko/docs/helm/helm_completion_bash.md, content/ko/docs/helm/helm_completion_fish.md, content/ko/docs/helm/helm_completion_zsh.md, content/zh/docs/helm/helm_completion_bash.md, content/zh/docs/helm/helm_completion_fish.md, content/zh/docs/helm/helm_completion_zsh.md
Follow-up helm/helm#9718
Renew #1100
=> Improve rendering of commands for shell completion in translations

content/en/docs/helm/helm_show_crds.md
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> [en]Fix typo

content/en/docs/topics/registries.md
=> Update registry topic for Helm 3.7+

content/zh/docs/chart_template_guide/yaml_techniques.md
fix the translation problem and the issue No is :#1207
=> fix the translation problem

content/en/docs/chart_best_practices/dependencies.md
Resolves this [documentation](https://github.com/helm/helm/issues/10306) issue.
=> clarify pre-release version constraints

i18n/zh.toml
Signed-off-by: vinnyzhaowenyu <admin@zhaowenyu.com>
=> fix #1235 , Helm Chart as a Glossary when translated into Chinese

content/zh/docs/chart_best_practices/dependencies.md, content/zh/docs/chart_template_guide/function_list.md
=> Update Chinese docs.

content/ja/docs/community/developers.md
Translated `community/developers.md` in Japanese.
=> [ja] Translate community/developers.md

content/en/blog/2022-01-11-welcome-karen-chu.md
Signed-off-by: Matt Butcher <matt.butcher@fermyon.com>
=> Blog post announce Karen Chu as Org Maintainer

content/zh/docs/chart_template_guide/builtin_objects.md, content/zh/docs/chart_template_guide/getting_started.md
fix translation error about --dry-run code in getting_started.md.  更正…了一些关于--dry-run的翻译错误
Signed-off-by: PaulZhu <783725554@qq.com>
=> fix zh translation error about --dry-run code in getting_started.md. 

content/zh/docs/chart_template_guide/builtin_objects.md
Signed-off-by: Oscar Ding <dingbj91@hotmail.com>
=> chinese typo fix

content/en/docs/chart_template_guide/function_list.md, content/ko/docs/chart_template_guide/function_list.md, content/zh/docs/chart_template_guide/function_list.md
Replaces incorrect "proto" scheme with correct "http" scheme.
Signed-off-by: Evan Benshetler <ebensh@gmail.com>
=> Fix urlJoin documentation output to match input

content/en/blog/2022-02-28-storing-charts-in-oci.md
Good to get out there! Set a target date that feels realistic. Can move if needed.
Thanks @jdolitsky and @mattfarina for collaboration. Thanks @bridgetkromhout for review in HackMD.
For more history, see: https://hackmd.io/3ixHqHw5TyqcY9yXt1DPPA?view
=> Blog post announcing storing charts in OCI as a full feature

content/zh/docs/intro/install.md
=> [zh] Add scoop to Chinese doc

content/en/docs/topics/registries.md
Fix for a small typo of "System"
=> Fix typo in registries.md

content/en/blog/2022-04-19-tools-to-manage-helm-declaratively.md, content/en/docs/community/related.md, content/ko/docs/community/related.md, content/zh/docs/community/related.md
Signed-off-by: yxxhero <aiopsclub@163.com>
change helmfile repo address. 
see: https://github.com/roboll/helmfile#please-read-helmfile-has-moved-home
=> change helmfile repo address

i18n/en.toml
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> main page: remove mention of helm/charts

content/en/docs/intro/install.md
Signed-off-by: Ali Yousefi Sabzevar <aysabzevar@gmail.com>
=> add install helm with dnf/yum method on fedora.

content/en/docs/chart_template_guide/function_list.md
Closes #873  
I found these functions while working with helm this last week so I figured I would take a stab at documenting them!
Huge appreciation for everyone who makes this project possible :slightly_smiling_face:
=> Document fromYaml and fromJson

content/en/docs/topics/registries.md
Reorganized and added additional content around OCI support in Helm v3.8.0
=> Update registries.md with additional OCI information

content/en/docs/community/localization.md
Signed-off-by: Bishal das <70086051+bishal7679@users.noreply.github.com>
Fixes :- #1360
Closes :- #1360
=> Fixed typo in localization.md

content/en/blog/2022-10-14-helm-at-kubecon-na-22.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
=> Add blog post on Helm at KubeCon '22

content/en/blog/2022-10-14-helm-at-kubecon-na-22.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
=> Update Helm booth heading

content/fr/docs/_index.md, content/fr/docs/community/_index.md, content/fr/docs/howto/_index.md, content/fr/docs/topics/_index.md
Fix FR documentation -> https://helm.sh/fr/docs/
Signed-off-by: Maxime Guilbert <mx.guilbert@gmail.com>
=> #1375 - Fix FR documentation

content/en/docs/community/related.md
Signed-off-by: Andrey Pokhilko <andrei@komodor.io>
=> Add Helm Dashboard to the list of plugins

content/zh/docs/community/related.md
=> [zh] Update Chinese doc.

content/zh/docs/helm/helm_dependency.md
=> Fix dependencies alignment in zh docs

content/en/blog/2022-11-14-welcome-yxxhero.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
=> Add blog post welcoming yxxhero

themes/helm/assets/js/app.js
Fix for https://github.com/helm/helm-www/issues/1373
=> Fix active link in sidebar

content/en/docs/chart_template_guide/function_list.md
@yxxhero 
see:
#1202 
#489
helm main repo issues: 
#4262
#10818
=> Adding toYaml docs

content/en/docs/chart_template_guide/getting_started.md
Signed-off-by: Richard Hooper <22979170+PixelRobots@users.noreply.github.com>
=> fix layout

content/en/docs/community/related.md
Signed-off-by: Arthur Berezin <2787296+rtpro@users.noreply.github.com>
=> Adding helm-release plugin

content/en/docs/chart_template_guide/helm_ignore_file.md
=> Improve helmignore docu

content/es/docs/howto/chart_releaser_action.md
Hello, 
I want to collaborate with the translation into Spanish of your documentation. I have started with a simple file, the chart_releaser_action.md
Cualquier error me comentáis para poder seguir la misma línea en las siguientes traducciones.
Un saludo
=> Spanish translation of the file chart_releaser_action.md

content/en/docs/topics/registries.md
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
=> Add "zot" as OCI-based registry which supports helm charts.

content/zh/docs/chart_template_guide/accessing_files.md, content/zh/docs/chart_template_guide/subcharts_and_globals.md, content/zh/docs/topics/library_charts.md
=> [zh] Update Chinese docs.

content/en/docs/topics/version_skew.md
v3.10 links client-go v0.25.x
https://github.com/helm/helm/blob/release-3.10/go.mod#L44
=> Add release v3.10 version skew

content/ko/docs/chart_best_practices/dependencies.md
Signed-off-by: Youngkook Kim <kyg9823@gmail.com>
=> Fixed a type on dependencies.md for korean.

content/ko/docs/chart_template_guide/values_files.md
Signed-off-by: Youngkook Kim <kyg9823@gmail.com>
=> Translate values_files.md for korean.

content/ja/docs/chart_best_practices/pods.md
* translated best practices pods into Japanese
I hope this will help helm users :)
Signed-off-by: yasunaga shuto <yasunaga.shuto@gmail.com>
=> translated best practices pods into Japanese

content/en/docs/topics/registries.md
Signed-off-by: galzil1 <70253799+galzil1@users.noreply.github.com>
=> Added JFrog Artifactory as OCI supported registry

content/en/docs/chart_template_guide/function_list.md, content/en/docs/chart_template_guide/notes_files.md
Signed-off-by: Billy Kern <william.j.kern@gmail.com>
=> fix minor typos

content/zh/docs/helm/helm_dependency.md, content/zh/docs/helm/helm_install.md, content/zh/docs/helm/helm_template.md, content/zh/docs/helm/helm_upgrade.md
=> [zh] Updating Chinese docs for 3.11.1

content/en/docs/topics/registries.md
Add link to blog post which has a Helm example.
=> Docker Hub has OCI artifact support now

content/en/docs/howto/chart_releaser_action.md, content/es/docs/howto/chart_releaser_action.md, content/zh/docs/howto/chart_releaser_action.md
Updated examples for GitHub Actions to match more recent versions.
Trying to help devs copying this as their default pipeline. Hope it helps!
=> Update GitHub Actions examples

content/en/docs/topics/charts.md
https://fantastic-charts.storage.googleapis.com return this:
```
AccessDeniedAccess denied.Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).{ document.currentScript.dataset.injected = true; const o = JSON.parse(decodeURIComponent(escape(atob('eyJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoWDExOyBVYnVudHU7IExpbnV4IHg4Nl82NDsgcnY6MTAwLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTAwLjAiLCJhcHBWZXJzaW9uIjoiNS4wIChYMTEpIiwicGxhdGZvcm0iOiJVYnVudHUiLCJ2ZW5kb3IiOiIiLCJwcm9kdWN0IjoiR2Vja28iLCJ1c2VyQWdlbnREYXRhIjoiW2RlbGV0ZV0iLCJvc2NwdSI6IlVidW50dSIsInByb2R1Y3RTdWIiOiIyMDEwMDEwMSIsImJ1aWxkSUQiOiIyMDE4MTAwMTAwMDAwMCJ9')))); if (o.userAgentDataBuilder) { const v = new class NavigatorUAData { #p; …
```
=>  google api is forbidden

content/en/docs/community/developers.md
Closes https://github.com/helm/helm-www/issues/1450
- Removes references to vendor/ directory
- Updates git conventions section
Signed-off-by: Lucas Rodriguez <lucas.rodriguez9616@gmail.com>
=> Update developer guide docs

content/es/docs/topics/advanced.md, content/es/docs/topics/architecture.md
* Spanish translation of the file advanced.md
* Spanish translation of the file architecture.md
Signed-off-by: Manuel Vergara <manuel@vergaracarmona.es>
=> Spanish translation of docs

content/en/docs/chart_template_guide/named_templates.md, content/ko/docs/chart_template_guide/named_templates.md
Adds documentation about the issue described here: https://github.com/helm/helm/issues/11561
I'm open to changing the wording, or a different approach to the workaround. Please let me know any feedback you may have.
Signed-off-by: Josh Lubawy <jlubawy@gmail.com>
=> Add paragraph about named templates in different chart versions

content/en/docs/intro/CheatSheet.md
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to …
=> Cheatsheet for Helm

content/en/docs/topics/rbac.md, content/ko/docs/topics/rbac.md, content/zh/docs/topics/rbac.md
This pull requests fixes the issue raised here https://github.com/helm/helm-www/issues/1465.
=> Fix k8s link in page https://helm.sh/docs/topics/rbac/ 

content/en/blog/2023-05-15-helm-oci-mediatypes.md
Added new blog on Helm's OCI MediaTypes
=> OCI MediaType blog

content/en/docs/community/related.md
Adding a link to a new plugin that we just have open sourced.
=> Adds dt to the list of plugins

content/en/docs/glossary/_index.md
related issue: https://github.com/helm/helm-www/issues/1488
=> add Chart Registry to the Glossary

content/en/docs/community/related.md
Hi. I have released a new Helm plugin [helm-chartsnap](https://github.com/jlandowner/helm-chartsnap) - Snapshot testing plugin for Helm charts.
Please approve it to be added in plugins list in Related Projects and Documentation if it's OK.
Thank you.
=> Add plugin `helm-chartsnap`

.gitignore, content/fr/docs/intro/CheatSheet.md
Translation of page `CheatSheet.md` in `fr` French
=> CheatSheet Translation in French

config.toml
This PR attempts to fix artifacthub.io links in helm.sh
=> fix artifacthub.io links in config.toml

content/en/docs/chart_template_guide/debugging.md
=> Fix misleading doc for helm install --dry-run

content/en/docs/chart_template_guide/builtin_objects.md
Follow up docs PR to the functionality add here: https://github.com/helm/helm/pull/9957
=> docs: Add Subcharts to builtin_objects.md docs

content/zh/docs/chart_template_guide/function_list.md
=> fix CN document links

content/en/blog/2024-03-14-cve-2019-25210.md
This was created from the collaborative doc.
=> Adding blog post in response to CVE-2019-25210

content/de/docs/intro/install.md, content/en/docs/intro/install.md, content/es/docs/intro/install.md, content/fr/docs/intro/install.md, content/ja/docs/intro/install.md, content/ko/docs/intro/install.md, content/pt/docs/intro/install.md, content/ru/docs/intro/install.md, content/zh/docs/intro/install.md
Fixes #1471 by adding the installation instructions for Winget. Because I don't understand most of the languages that the documentation is provided for, it would be nice if someone could check that I didn't make any blatant error, especially for languages like Korean or Japanese.
=> Add installation instructions for Winget

content/en/docs/community/related.md
Added Helmper to the list of community projects using Helm
=> Update content/eu/related.md with new community project

content/en/docs/topics/registries.md, content/zh/docs/topics/registries.md
https://helm.sh/docs/topics/registries/#use-hosted-registries
[JFrog Artifactory](https://www.jfrog.com/confluence/display/JFROG/Docker+Registry)
Link updated >> https://jfrog.com/help/r/jfrog-artifactory-documentation/helm-oci-repositories
=> corrected the JFrog Artifactory link

content/de/docs/intro/install.md
In German translation update commands to install on debian to match the English documentations
=> Documentation-Translation-German Update commands to install on debian

OWNERS
Ref email: https://lists.cncf.io/g/cncf-helm/message/491
=> Move hickeyma to emeritus

content/en/docs/intro/CheatSheet.md, content/es/docs/intro/CheatSheet.md, content/fr/docs/intro/CheatSheet.md, content/zh/docs/intro/CheatSheet.md
bug fix: https://github.com/helm/helm-www/issues/1609
update incorrect command in Helm doc
=> update incorrect command in helm doc

content/en/docs/community/related.md
Adding a link to a new Helm plugin that we have open sourced.
=> Add helm-migrate-values to list of plugins

themes/helm/assets/sass/docs-responsive.scss, themes/helm/assets/sass/helm-home.scss
=> Chore: fix Home overview section to show a transparent background color on IOS

content/en/docs/intro/using_helm.md
=> Chore: update docs to highlight repo URL

content/en/blog/2024-11-08-experience-helm-release-kubecon-na-24.md
Added blog for Helm release for KubeCon NA 2024
=> Helm release KubeCon blog

config.toml, content/en/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md, content/en/blog/2020-04-30-celebrating-helms-cncf-graduation.md, content/ko/blog/2020-04-30-celebrating-helms-cncf-graduation.md, content/ko/docs/faq/_index.md, netlify.toml, themes/helm/layouts/partials/css.html, themes/helm/layouts/partials/js.html, themes/helm/layouts/partials/nav-i18n.html
Close #1539, Close #1529, Close #1288, resolve #1630, resolve #1482
This PR proposes to use the up-to-date version of Hugo
=> Use up-to-date Hugo v.0.138

content/en/docs/topics/provenance.md
=> fix typo in provenance.md

content/en/code/helm-v3.md
https://github.com/helm/helm/tree/dev-v3
=> Helm v3 development now happens on the dev-v3 branch

content/en/docs/topics/plugins.md
**What this PR does / why we need it:**
This PR adds the docs for https://github.com/helm/helm/pull/12962.
**Special notes for your reviewer:**
I've tried to align the plugin docs to the chart docs.
=> feat: Added docs for multi-platform plugin hook support

content/en/docs/community/related.md, content/zh/docs/community/related.md
Adding K8Studio as a related tool to Helms since a good part of the tool is dedicated to  a full  Helm manager.
=> Adding K8Studio to community related tools

content/en/docs/community/related.md
Added helm cel(https://github.com/idsulik/helm-cel) plugin to the helm plugins list
=> Add helm-cel plugin to related.md

content/zh/docs/sdk/_index.md, content/zh/docs/sdk/examples.md, content/zh/docs/sdk/gosdk.md
the golang sdk doc  is missing for Chinese, add it
=> Add gosdk example to zh doc

OWNERS
Asa  core maintainer George would also like to help maintain the website, specifically reviewing PRs related to Helm core but also review in general.
=> Add gjenkins8 to helm-www OWNERS

OWNERS
I was actually not officially on the owners list for the website
Would like to continue helping with this with that in mind
I realize I'll need to rebase after #1775 but adding this now to start the process.
=> Add scottrigby to helm-www OWNERS
