helm/helm-www

_config.yml

`Gemfile.lock` ahoy! and `script/` is not a part of the jekyll site.

Just a little bit of CI cleanup

---

javascripts/konami.js
javascripts/ui.js

Konami code ga event was being fired at event registration (i.e., for each page view). Moved into the konami.js code itself.

a little too quick to release the kraken

---

_sass/_helm.scss

iOS/Safari at least, and I'd expect most mobile browser implementations, doesn't do anything with a `irc://`-prefixed hyperlink.

style(index) disabling irc link for mobile media query

---

package.json

this isn't really a node project, but we may as well correctly publish the new canonical git url

chore(metadata) update package.json

---

_layouts/index.html

With 0.2.0, we should call out `repo` command, since that is an important feature!
/cc @jackfrancis

doc(repo): add repo example

---

_layouts/index.html

using `sh` gives errors on some Linux OSes

fix(index): used bash for "get.helm.sh" script

---

_layouts/index.html

The conversation and help seems to be at the slack channel, not at the IRC (in fact, it is empty).
Change the link to avoid confusion.

Change irc link to slack channel

---

rootfs/Dockerfile

`make build-image` is broken since caddyserver's download URL was changed recently.
The prometheus plugin isn't listed now, but it's not essential according to @ultimateboy.

fix(Dockerfile): move to new caddyserver download URL

---

index.html

Removing the urls from the "supported by Microsoft" logos.
One of the links was broken, and there's no need to link to the current page for those logos anyway.

Remove helm.sh links from "supported by Microsoft" logos

---

docs/gulpfile.js
docs/script/deploy
docs/script/install

There's an issue with `gulp` tasks sequencing that's [affecting some builds (#51)](https://github.com/helm/helm-www/issues/51), where the directory setup does not complete.
This PR splits the gulp tasks so that the directory setup waits for the fetching of the docs to complete before running, to ensure the correct sequence is followed.

Update build scripts

---

docs/config.toml
docs/themes/helmdocs/layouts/partials/offcanvas.html
docs/themes/helmdocs/layouts/partials/sidebar.html

* update the offcanvas template to fix the docs menu for mobile and small screens (closes #54) 
* remove the home link from the menu (config.toml)
* add the home link into theme templates, as a relative `site.BaseUrl` value (closes #49)

Update docs menu to fix #49 and #54

---

index.html

Update to #65 and #67.
Added charts link per discussion in https://github.com/helm/helm-www/pull/65#issuecomment-344450733.
Changed string from "contributors" to "maintainers" per existing language in CONTRIBUTING.md files in each repo (I think the idea is that "contributors" are much wider community than maintainers, and it's open to anyone to contribute).

Update contributors/maintainers line

---

docs.helm.sh/gulpfile.js

Required to enable [#4041](https://github.com/kubernetes/helm/pull/4041).
This PR ensures the site homepage doesn't get overwritten by the docs README.md

update build task to remove readme.md as homepage

---

docs.helm.sh/gulpfile.js

It turns out that this is messing with the core documentation. Any time "rbac" is mentioned,
it is immediately replaced with #role-based-access-control which is messing with the doc
text in certain areas.
See https://docs.helm.sh/using_helm/#example-service-account-with-cluster-admin-role for an example

remove rbac pipeline link replace

---

brigade.js

This updates the script for Brigade's [brigly](https://github.com/deis/brigly-actions) bot, to point to the prod storage account for helm.sh and docs.helm.sh

update brigade script for brigly with prod storage acc

---

brigade.js
helm.sh/Gemfile

Updates the brigade.js and Gemfile to use the same version of Ruby.
The mismatch is triggering errors in the build task in #103.

[helm.sh] edit ruby versioning for build task

---

brigade.js
helm.sh/Gemfile

This is a follow up to #105 - switching the docker image for helm.sh from node to ruby.

[helm.sh] update ruby image and version

---

helm.sh/_posts/2018-07-24-helm-emeritus-rimus.md

Adds a new blog post: 
> Rimus Mocevicius (rimusz) has become the fourth Helm Emeritus Maintainer.

[helm.sh] blog post - emeritus maintainer rimas mocevicius

---

docs.helm.sh/themes/helmdocs/layouts/partials/header.html
docs.helm.sh/themes/helmdocs/layouts/partials/topbar.html

Updates the `title` tag in the hugo theme `head`, to properly output the site / section [title](https://gohugo.io/functions/title/#readout).
Fixes #143.

[docs.helm.sh] #143 restore title tag in head

---

helm.sh/README.md
helm.sh/_layouts/post.html
helm.sh/_posts/2018-06-01-cncf.md
helm.sh/_posts/2018-07-23-bring-helm-home.md
helm.sh/_posts/2018-07-24-helm-emeritus-rimus.md
helm.sh/_posts/2018-08-27-helm-switch-dco.md
helm.sh/_posts/2018-09-07-new-gov-and-elections.md
helm.sh/_posts/2018-09-25-chart-testing-intro.md
helm.sh/_posts/2018-10-04-helm-org-maintainers.md
helm.sh/blog/index.html

- Found that the helm blog was a bit difficult to read since we weren't using the "read more" function that was configured in the Jekyll installation, making some posts very very long on the main blog page. I added a "read more" break to most posts (except a very short one), designated with a small right arrow and some aria accessibility clarifications.
- Noted that `author` and `authorname` were used inconsistently; I normalized and documented them. I removed a hyphen which ends up trailing awkwardly if someone doesn't use `author`, and added some missing author names.
- Fixed the broken links to Older/Newer posts (which had to do with blobstore not automatically checking `index.html`) and also fixed a couple of typos.

Blog usability & clarifications

---

docs.helm.sh/themes/helmdocs/static/src/sass/docs-footer.scss

It's a small detail, but this CSS rule causes the footers to overlap, which results in an annoying double-scrolling in some of the longer pages.

Remove negative margin to prevent footer overlap and double-scrolling

---

helm.sh/_posts/2018-10-04-helm-org-maintainers.md

Add Josh Dolitsky and Scott Rigby
Signed-off-by: Roc Chan <roc@imroc.io>

[Blog] update org maintainers

---

docs.helm.sh/config.toml

URL paths are incorrect in the following menus:
Using Helm, Helm Commands, Charts and Developing Templates
When click on submenu for the above menus, if you try to right click
on another menu to open in another tab/window, it will not resolve to the
correct url as it does not dereference the current url path correctly.
Closes #4698 in Helm issues
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

Fix urls for some menus

---

docs.helm.sh/gulpfile.js

This PR cleans up a bunch of 404 link issues, updating the gulp task which adapts the markdown doc files to better suit the Hugo site generator. Closes the following issues:
Closes #64 #92 #131 #157 #161.
--
These links on the Helm Command docs ([example](https://docs.helm.sh/helm/#see-also)) haven't been working in Hugo due to differences between the source and how Hugo formats things. This PR adds a task to circumvent the issue, a regex that swaps the `_` for `-` in links on those docs.
Closes #60 and #133.

Broken URL Patching

---

docs.helm.sh/themes/helmdocs/layouts/index.html

Typo fix for the name of the site we're pointing to - daemonza, not deamonza.

Typo fix - doc site name

---

docs.helm.sh/config.toml

The hugo configuration settings were _under_ the params section which in TOML means that they are part of params, so hugo was completely ignoring them all.
I have moved them up a bit in the file so that they are parsed as root level values in the file. Now the pluralizeListTitles setting (along with a few others) will be applied by Hugo properly.

Fix "helms" showing in in the title and header of the docs

---

docs.helm.sh/config.toml

This is a follow up to #176 - the `relativeURLs` option in the site config was throwing errors when hugo was building the site. Removing it will fix the builds.

Resolve hugo build error

---

themes/helm/layouts/partials/offcanvas.html

On desktop, the side navigation work with the new structure (from the site changes #162), but on mobile the menu is in the old format and the sub category links need updating.
This adds `docs` to the path of those links to fix the menu on mobile.

fix submenu links for new structure

---

gulpfile.js

Updates the find and replace task that makes internal links work with the Hugo site structure.
Fixes #181.

[#181] update the url replace task for helm command docs (helm > helm)

---

README.md
content/blog/2018-06-01-cncf.md
content/blog/2018-07-23-bring-helm-home.md
content/blog/2018-07-24-helm-emeritus-rimus.md
content/blog/2018-08-27-helm-switch-dco.md
content/blog/2018-09-07-new-gov-and-elections.md
content/blog/2018-09-25-chart-testing-intro.md
content/blog/2018-10-04-helm-org-maintainers.md
content/blog/2018-12-11-helm-hub.md
content/blog/2019-01-14-chartmuseum-security-notice.md
content/blog/2019-01-14-helm-security-notice.md

I noticed that a subtle difference between Jekyll and Hugo is showing up in how we're handling the URLs for the Helm blog. This means that all previous-to-the-Hugo-migration links to specific blog posts are currently broken.
This problem can be observed if you hover over the blog post URLs the wayback machine shows used to exist: https://web.archive.org/web/20190203185202/https://helm.sh//blog/
It also shows up on the live site right now because the "new helm governance" link is broken on https://helm.sh/blog/2018-10-04-helm-org-maintainers/
Background on why this happened: Jekyll has a concept of permalink in the frontmatter for individual blog posts (https://jekyllrb.com/docs/permalinks/). Hugo handles URL parsing in different ways, leading to that permalink line in each blog post being …

Fixing blog URLs

---

README.md
content/blog/2018-12-11-helm-hub.md

Blog images appear to be published in a different place than previously. This reflects that reality; however, it's possible that wasn't intentional. In that case, it should be revisited, but meanwhile this could be a temporary fix that restores the missing image on https://helm.sh/blog/intro-helm-hub/.

Fixing broken image link

---

config.toml
content/code/helm.md
themes/helm/layouts/code/single.html

Enable `go get helm.sh/helm/...`

feat(go-imports): configure vanity go import path

---

gulpfile.js

The TOC links are broken due to differences in how titles and #anchors are formatted in markdown between GitHub and Hugo. This updates the site build task to modify the urls to work correctly with the Hugo docs site.
Fixes #190.

[#190] update build task to correct best practices toc

---

content/blog/2018-06-01-cncf.md
content/blog/2018-07-24-helm-emeritus-rimus.md

I noticed that https://twitter.com/HelmPack/status/1002577607135617024 has a link to https://helm.sh/helm-enters-the-cncf/index.html which 404s because we aren't rewriting URLs like that. 
I think this issue is being caused by that difference in Jekyll permalinks vs Hugo slugs (like in https://github.com/helm/helm-www/pull/183) - when I did those rewrites, I handled them all with the `/blog/` in the URL. But we need to cover the (as far as I can tell) two cases without that.

Fixing broken links on blog

---

themes/helm/static/src/sass/docs-home.scss
themes/helm/static/src/sass/docs-responsive.scss

Currently there's a glitch on helm.sh when you view the site on a mobile device. The vast open seas are a little _too_ vast.
This PR corrects the positioning of elements:
---
Thanks @karenhchu for flagging the bug.

fix homepage positioning for mobile layouts

---

themes/helm/layouts/blog/list.html
themes/helm/layouts/blog/single.html
themes/helm/layouts/docs/list.html
themes/helm/layouts/index.html
themes/helm/layouts/partials/banner.html
themes/helm/layouts/partials/topbar.html
themes/helm/static/src/sass/docs-home.scss
themes/helm/static/src/sass/docs-responsive.scss
themes/helm/static/src/sass/docs-sidebar.scss
themes/helm/static/src/sass/docs-topbar.scss
themes/helm/static/src/sass/helm-home.scss

Rolled back #220 until we're read to flip the switch. This is a duplicate of that PR.
This adds a sticky banner to the site which states:
* highlights the coming of Helm 3
* states what version of Helm you are currently viewing info on
* links to the other version
---
"You are viewing Helm 2 (latest stable).   Helm 3.0.0-alpha.1 is here.   Visit the v3 docs or read the blog for details."
---
V3 links go to [v3.helm.sh](https://v3.helm.sh/), which has a different message and in turn links back to V2 (aka http://helm.sh)

[v3] add a sticky banner for helm 2 and helm info

---

themes/helm/layouts/code/single.html

Hello, as discussed on #helm-dev slack, this pull request fixes meta tags for go tools.
More info on go-import meta tag: https://golang.org/cmd/go/#hdr-Remote_import_paths
And go-source meta tag: https://github.com/golang/gddo/wiki/Source-Code-Links

fix(go-import): fix go path on meta tags

---

OWNERS

This adds a list of repo maintainers, based off of the existing [web team](https://github.com/orgs/helm/teams/web/members) and core [Helm Org](https://github.com/orgs/helm/teams/helm-org-maintainers/members) personnel.
Addresses #227

add an OWNERS file

---

themes/helm/static/src/sass/docs-content.scss

Fix for #233. 
Having horizontal scrolling within code snippets is standard web practice, but I do see how lots of sideways scrolling is annoying when the code runs far longer than the reading pane.
The website layout limits line length intentionally, which imposes whitespace on large screens. This approach is to [aid readability of page copy](https://uxplanet.org/10-tips-on-typography-in-web-design-13a378f4aa0d#f63f), but does not suit the code sections. 
**Before:**
The proposed solution here widens the code boxes to the right towards the edge of the viewport, to give long lines of code more space. This will maintain a pleasant line-length for the normal text, but expand for the code.
**After:**

#233 (docs): Improve layout for code line length

---

gulpfile.js

I noticed running gulp will erase the content/docs/ directory during the `clean` task. This is a legacy of the previous cloning of the docs from helm/helm, and should be removed now as part of #230.
This is a short term fix until #237 (Hugo Pipes) is implemented and Gulp is removed.

[230] ensure gulp does not wipe away content/docs/

---

themes/helm/static/src/sass/docs-sidebar.scss

Part of the fix for #240, this corrects a layout bug that rendered the search box on the docs impossible to click into.
---
This fixes search for the v2 docs - I will follow up with a separate fix for the v3 docs.

[#240] make search tool clickable again

---

themes/helm/static/src/sass/docs-layout.scss

This PR addresses the weird Firefox scrolling issue in #139.
The suggestion by @wisniewskit is applied here and solves the strange frame focus issue I was stumped by. 
---
Closes #139.

[#139] change overflow value to resolve firefox keyboard scroll issue

---

layouts/docs/list.html
layouts/docs/single.html

This PR is the first in a series of layout fixes to restore the Hugo templates for the docs. During the build pipeline changes in #230, there were also html and css changes to the theme files that bumped a few things around.
Live site:
After this patch:
---
I will follow up with a separate PR to tidy up the _category_ landing pages (like [this one](https://v3.helm.sh/docs/topics/chart_template_guide/)).
---

[#230] fix the grid layout for v3 docs

---

themes/helm/layouts/index.html

Looks like the link for the weekly developer call on the website was an old link. i suspect people were finding the right link from https://github.com/helm/helm/blob/master/README.md#community-discussion-contribution-and-support but if they looked on https://helm.sh it was wrong.

Updating zoom link for weekly call

---

config.toml
themes/helm/layouts/partials/nav.html

This PR enables updating the config selector via the site config rather than hard-coding those values in the `nav` partial

Set versions via site configuration

---

content/code/chartmuseum.md

Attempting to prevent this error:
```
$ go get -u helm.sh/chartmuseum
go: creating new go.mod: module github.com/helm/helm-www
go get helm.sh/chartmuseum: unrecognized import path "helm.sh/chartmuseum" (parse https://helm.sh/chartmuseum?go-get=1: no go-import meta tags ())
```
Is there anything else needed for this?

Make vanity url usable by chartmuseum

---

config.toml
themes/helm/assets/sass/docs-home.scss
themes/helm/assets/sass/docs-responsive.scss
themes/helm/assets/sass/docs-sidebar.scss
themes/helm/assets/sass/docs-topbar.scss
themes/helm/assets/sass/helm-blog.scss
themes/helm/assets/sass/helm-home.scss
themes/helm/layouts/blog/list.html
themes/helm/layouts/blog/single.html
themes/helm/layouts/docs/list.html
themes/helm/layouts/index.html
themes/helm/layouts/partials/banner.html
themes/helm/layouts/partials/nav.html
themes/helm/layouts/partials/topbar.html

* denotes latest releases as `2.14.3` and `3.0.0.beta.1`, this replaces PR #256 which got stuck with a conflict
* restores the sticky v2/v3 banner to the homepage *
The sticky banner was taken off the homepage when the version dropdown menu was added to the [site](https://github.com/helm/helm-www/commit/a392fbc9496223b2cc39c1423c575d179a72d8b3). Adding it back here because I think both are useful to highlight where things are.

fix sticky banner for v2 <-> v3 site links

---

config.toml
themes/helm/assets/sass/docs-topbar.scss
themes/helm/layouts/partials/nav.html

The `$primary` version needs fixing asap - live site shows up as v3 instead of v2! 
I should have spotted this in #269, sorry.

docs(bug): correct the v2 current version

---

themes/helm/assets/sass/docs-sidebar.scss

One more tweak: the button's contrast ratio was failing accessibility checks, so I reversed the color scheme with color variables to make it more legible.
Hopefully this drives some increased engagement, too? The original button kinda blended in and didn't look too inviting (almost disabled).
Signed-off-by: Ben Radcliffe <bsradcliffe@gmail.com>

Improve contrast accessibility of contribute button

---

content/docs/howto/charts_tips_and_tricks.md

Now that we are deprecating the `--recreate-pods` flag, the documentation
now reflects the better way for rolling deployments automatically

Updates documentation for automatically rolling deployments

---

content/docs/intro/v2_v3_migration.md

This document describes how to migrate from Helm v2 to v3.

Add migration documentation

---

content/docs/intro/v2_v3_migration.md

(The change on line 60 is `the the` → `the`.)

Fix typos in v2–v3 migration documentation

---

content/docs/faq.md

Links in faq.md were broken, since they were pointing to somewhere else
than where the respective resources are located on the webpage right
now.
Go here and try clicking the links: https://v3.helm.sh/docs/faq/
Signed-off-by: Andreas Lindhé <andreas@lindhe.io>

Fix broken links to docs pages

---

content/docs/intro/quickstart.md

This removes the discussion of `helm init` in the quickstart, and adds a section about adding the stable repository.

fix: Update docs to remove 'helm init' and add 'helm repo add'

---

content/docs/community/release_checklist.md
content/docs/faq.md
content/docs/glossary.md
content/docs/intro/install.md
content/docs/topics/plugins.md

Removes all non-autogenerated references to `helm init`.
It appears that the automatically generated HTML and Man pages need updating.

fix: remove references to helm init

---

content/docs/faq.md
content/docs/topics/chart_repository.md
content/docs/topics/charts.md
content/docs/topics/plugins.md

Updated references to `HELM_HOME` to talk about XDG directories.

fix: updated references about HELM_HOME to use XDG_*

---

content/code/helm-v3.md

With Go modules and packages with a major version greater than 1
the major version needs to be in the path. In Helm's case this
is a sort of virtual path and not on disk. The vanity redirect
needs to reflect this new version.
Fixes #300

Add vanity url for helm v3 with Go modules

---

config.toml
themes/helm/layouts/partials/banner.html

This way we don't have to update the banner each time a new version of Helm is released.

Helm 3: reference Helm 3 rather than specific version

---

config.toml
themes/helm/layouts/partials/banner.html

This way we stop needing to update the banner each time a new Helm release is out.

Helm 2: reference Helm 3 rather than the "latest" release

---

content/docs/intro/quickstart.md

install: requires release name or --generate-name argument
`helm install [NAME] [CHART] [flags]`

fix: Update docs to include generate-name argument

---

README.md
content/docs/community/developers.md
content/docs/faq.md
content/docs/howto/charts_tips_and_tricks.md
content/docs/intro/install.md
content/docs/intro/rbac.md
content/docs/intro/using_helm.md
content/docs/topics/chart_best_practices/dependencies.md
content/docs/topics/chart_best_practices/pods.md
content/docs/topics/chart_best_practices/templates.md
content/docs/topics/chart_repository.md
content/docs/topics/chart_template_guide/accessing_files.md
content/docs/topics/chart_template_guide/builtin_objects.md
content/docs/topics/chart_template_guide/control_structures.md
content/docs/topics/chart_template_guide/debugging.md
content/docs/topics/chart_template_guide/functions_and_pipelines.md
content/docs/topics/chart_template_guide/named_templates.md
content/docs/topics/chart_template_guide/subcharts_and_globals.md
content/docs/topics/chart_template_guide/values_files.md
content/docs/topics/chart_template_guide/variables.md
content/docs/topics/chart_template_guide/yaml_techniques.md
content/docs/topics/chart_tests.md
content/docs/topics/charts.md
content/docs/topics/charts_hooks.md
content/docs/topics/plugins.md
content/docs/topics/provenance.md
content/docs/topics/registries.md

* Improve syntax highlighting
* Use space after/before `{{`/`}}` to be consistent
with the scaffolding chart and with what we require in the
charts repo

Improve documentation consistency

---

themes/helm/layouts/docs/list.html

Looks like this change didn't get migrated over.
https://github.com/helm/helm/pull/6067

Fix broken link in Quicklinks

---

themes/helm/assets/sass/docs-content.scss
themes/helm/assets/sass/docs-footer.scss
themes/helm/assets/sass/docs-layout.scss
themes/helm/assets/sass/docs-responsive.scss
themes/helm/assets/sass/docs-sidebar.scss
themes/helm/layouts/docs/list.html
themes/helm/layouts/docs/single.html
themes/helm/layouts/partials/offcanvas.html

This PR adds a bunch of CSS fixes to the current `v3.helm.sh` docs theme, to fix these issues: #247 #248 #249 #297 #327
Documentation landing pages no longer use the home page template that was applied in #230 
The homepage design (waves, boat etc) shouldn't appear on pages that prioritize information. These pages display dark text on a clear background, and Quicklinks are now displayed as a tabular list of links rather than the square panels which were going askew.
* grid layout fixed for mobile no longer askew 
* mobile menu content updated to render the new menu 
* CNCF footer alignment is visible once again
---
Screenshot:
---

docs(theme): fix the v3 docs landing pages

---

content/docs/topics/plugins.md

Many of the env vars were dropped or updated in Helm v3. This updates
all environment variables and takes care of a few other changes

Updates plugin documentation with current env vars

---

content/docs/topics/kubernetes_distros.md
content/docs/topics/rbac.md
content/docs/topics/v2_v3_migration.md

Advanced topic guides like role-based access control and the migration path from Helm 2 belong in the topic guide. Introductory guides are meant to introduce the user to basic concepts like "How do I use Helm?" and "How do I install Helm?"

ref(docs): move some documents to the topic guides

---

content/docs/intro/quickstart.md

This section has been removed now that Tiller is no longer a part of Helm 3. More advanced configuration of thei user's Roles and RoleBindings are covered in the topic guide for Role-based Access Control (see #337), but this is no longer a mandatory part of the quickstart guide. This is now an implementation detail based on how Kubernetes was configured.

fix(docs): remove section "Understanding your Security Context"

---

.gitignore

The idea folder contains config files for JetBrains IDEs like GoLand, IntelliJ and others.
Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>

add idea folder to .gitignore

---

config.toml
themes/helm/layouts/partials/banner.html

Moves the `stable` label from v2 to v3.
Points v2 references at v2.helm.sh
Points v3 references at helm.sh

change references to v2 (older version) and v3 (stable)

---

README.md
themes/helm/layouts/partials/sidebar.html

Updates the readme for `helm-www` with notes on Helm3 
* corrected location of docs (for v2 and v3) 
* updated dev and deployment info
* minor content clean up, reordered sections
* added notes on contributing, code of conduct
---
Here's the [corresponding PR for the v2 Readme](https://github.com/helm/helm-www/pull/348).
Closes #342.

Update v3 Readme

---

README.md

Updates the Readme for v2 (current master) with clarifications about where the docs are found and edited. Also updates the language and urls to treat this version of the website as archival ([v2.helm.sh](https://v2.helm.sh/)).
---
Here's the [corresponding PR for the v3 Readme](https://github.com/helm/helm-www/pull/345/).
Fixes #342.
---

Update v2 Readme

---

themes/helm/layouts/index.html

Several links were hardcoded to `helm.sh` when they should've linked to `/docs`. This way, each version of the landing page will refer to its own documentation.

fix(index): fix docs link

---

content/docs/community/developers.md

remove instructions for 'make docs', which is gone

---

content/docs/community/developers.md

Also, remove a rather unhelpful section on using minikube.

remove docker-build instructions for tiller

---

content/docs/community/developers.md
content/docs/community/history.md
content/docs/community/related.md
content/docs/howto/chart_repository_sync_example.md
content/docs/howto/charts_tips_and_tricks.md
content/docs/intro/_index.md
content/docs/intro/getting_started.md
content/docs/intro/install.md
content/docs/intro/quickstart.md
content/docs/intro/using_helm.md
content/docs/topics/architecture.md
content/docs/topics/chart_best_practices/_index.md
content/docs/topics/chart_repository.md
content/docs/topics/chart_template_guide/_index.md
content/docs/topics/chart_tests.md
content/docs/topics/charts.md
content/docs/topics/charts_hooks.md
content/docs/topics/kubernetes_distros.md
content/docs/topics/plugins.md
content/docs/topics/provenance.md
content/docs/topics/rbac.md
content/docs/topics/registries.md

Adds [hugo aliases](v) to pages that have been relocated in v3 docs.
The v3 docs have a different structure with some new directories (mostly `/intro` and `/topics`) and reorganization of content. These redirects are to try and catch as many of the old urls as possible (esp useful for things like links from external sources) and send users to a suitable destination.
e.g.
```
https://helm.sh/docs/using_helm/#quickstart-guide -> https://helm.sh/docs/intro/
https://helm.sh/docs/chart_best_practices/        -> https://helm.sh/docs/topics/chart_best_practices/

add hugo alias redirects for applicable v2 urls

---

content/docs/topics/chart_best_practices/templates.md

The "incorrect" example was demonstrating proper syntax. :1st_place_medal: 

fix(templates): fix "incorrect" example

---

content/docs/topics/charts.md

Add back the removed apiVersion field to the Chart.yaml docs.
Added information on changes form v1 to v2 taken from the Migrating Helm v2 to v3 guide.
Closes #6342 in helm repo.
Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>

docs: add apiVersion v1 and v2 description to to Chart.yaml docs.

---

netlify.toml

Following the site version changes, the `/blog` pages are inaccessible due to a redirect loop caused by [this code](https://github.com/helm/helm-www/blob/master/netlify.toml#L23-L57).

[v3] fix /blog redirect loop

---

netlify.toml

Some small adjustments for the `v2.helm.sh` site.
* update references to different versions
* redirect v2.helm.sh/blog traffic to helm.sh/blog, to ensure users are presented with the latest content

[v2] site versioning adjustments

---

content/blog/2019-11-04-helm-security-audit-results.md

To clear up some ambiguite that arose, it was specifically noted
that the CNCF funded the 3rd party security audit.

Added that CNCF funded sec audit to the blog post

---

content/docs/intro/quickstart.md

By default, all resources and release history will be deleted. Add
flag `--keep-history` while uninstalling to keep the release history.
Reference: https://github.com/helm/helm/blob/release-3.0/cmd/helm/uninstall.go#L70

Fix uninstall default behavior

---

content/docs/intro/quickstart.md

It should be "helm inspect chart stable/mysql" instead of "helm inspect stable/mysql"

Fix helm inspect format

---

content/docs/intro/install.md

The homebrew formula name was changed from `kubernetes-helm` to just `helm` with the helm 3 release: Homebrew/homebrew-core#46708

Update homebrew formula name

---

config.toml

The CICD for kubernetes link was wrong and was the same as the daemonza one.
Use the medium link found in v2 docs.
Should close #397

Fix duplicate in quick links

---

content/docs/topics/chart_best_practices/conventions.md
content/docs/topics/chart_best_practices/custom_resource_definitions.md
content/docs/topics/chart_best_practices/dependencies.md
content/docs/topics/chart_best_practices/labels.md
content/docs/topics/chart_best_practices/pods.md
content/docs/topics/chart_best_practices/rbac.md
content/docs/topics/chart_best_practices/templates.md
content/docs/topics/chart_best_practices/values.md
content/docs/topics/chart_template_guide/accessing_files.md
content/docs/topics/chart_template_guide/builtin_objects.md
content/docs/topics/chart_template_guide/control_structures.md
content/docs/topics/chart_template_guide/data_types.md
content/docs/topics/chart_template_guide/debugging.md
content/docs/topics/chart_template_guide/functions_and_pipelines.md
content/docs/topics/chart_template_guide/named_templates.md
content/docs/topics/chart_template_guide/notes_files.md
content/docs/topics/chart_template_guide/subcharts_and_globals.md
content/docs/topics/chart_template_guide/values_files.md
content/docs/topics/chart_template_guide/variables.md
content/docs/topics/chart_template_guide/yaml_techniques.md

Hopefully resolves #405 by adding a `weight:` to each subtopic page and replicating the v2 docs order.
Signed-off-by: Stephen Brown II <Stephen.Brown2@gmail.com>

Add weights to topics with multiple pages

---

content/docs/intro/using_helm.md

Those `helm install` commands can mislead users, So I fix these, Make it more helpful for greenhand

fix some wrong commands

---

content/docs/topics/charts.md

As described the removal of `helm serve` in the [FAQ](https://helm.sh/docs/faq/#removal-of-helm-serve) we should remove it from the chart docs as well.

remove helm serve command from charts docs

---

config.toml

The 'quicklink' section should ideally highlight current and interesting topics, but they haven't changed in a long time. This PR changes the ones found on helm.sh/docs to address some of the common questions asked at KubeCon
- what is helm? -> link to the _Intro to Helm_ KubeCon 2019 talk
- what do I do to upgrade to helm 3?  -> link to the migration blog post
- is helm secure? -> link to the announcement about the security audit results

update the docs quicklinks with some common question topics

---

content/docs/topics/chart_best_practices/rbac.md

It makes more sense to have a component's service account values under itself in the values file.

Multiple service accounts example correction

---

content/docs/faq.md
content/docs/topics/chart_tests.md
content/docs/topics/charts_hooks.md
content/docs/topics/v2_v3_migration.md

This PR brings Helm docs up to date with the changes from https://github.com/helm/helm/pull/6054 and https://github.com/helm/helm/pull/6639.
- Note that `test-success` and `test-failure` hooks are deprecated in favor of `test`
- Update Helm test example to use a `Job` resource instead of a `Pod`
- Indicate that `crd-install` is no longer supported in Helm 3
- Suggest using [TTL controller](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) to clean up Job hooks
- Note that `before-hook-creation` is now the default hook deletion policy
- Warn that garbage collection behavior is subject to change and `helm.sh/resource-policy: keep` should be applied in situations where this is undesirable (see also https://github.com/helm/helm/issues/6364)
View rendered pages:
- …

Update hook and test documentation for Helm 3

---

content/docs/topics/charts.md

While reading the docs, I noticed the typo `where` in
> A `dependencies` field defining chart dependencies, which where  	
> located in a separate `requirements.yaml` file for `v1` charts
And so I set about fixing it. Then also noticed that:
- The workflow for deprecating charts was not formatted as a list but instead was joined with the previous paragraph
- The code blocks did not all have language specifiers
- The unordered lists were using inconsistent bullets (`-` and `*`) and indentation
- Various other whitespace was inconsistent in and around code blocks, headers, lists, and trailing lines
Results can be seen here: https://deploy-preview-406--helm-merge.netlify.com/docs/topics/charts/

charts.md: Fix typos, whitespace, markdownlint

---

themes/helm/assets/js/app.js

This PR solves #424 and resolves a javascript error on the docs site, which was caused by the search tool code being included a second time. 😊

[#424] remove duplicate javascript

---

content/docs/topics/chart_repository.md

The images for supporting the [Chart Repository guide](https://helm.sh/docs/topics/chart_repository/) are not correctly shown.
It may be due to a previous refactor, where the `images` folder used to be at the same level of the `chart_repository.md` documentation file.

[docs] Fix chart repository doc image paths

---

content/docs/topics/chart_best_practices/labels.md

Helm v3 is Tillerless. So, `managed by Tiller` is old description.

Fix description for `app.kubernetes.io/managed-by` label

---

content/docs/topics/v2_v3_migration.md

Fix `upgrade` command argument name in the migration guide.
As you know,
```
$ helm upgrade -h | grep history
--history-max int          limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)
```

Fix argument `--maxHistory` -> `--history-max`

---

content/docs/community/related.md

I'd like to offer up a unit testing plugin which uses the CNCF sponsored OPA/Rego policies as its DSL.
This adds a link in the docs so Helm users can better discover HCUnit as a testing option.

add link to hcunit plugin

---

content/blog/2019-10-30-helm-symlink-security-notice.md

The CVE assigned to this can be found at
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-18658
Adding the CVE id this was follows the method previously done.
In the future we made (should?) use the new system provided by
GitHub. This is an update to a post from prior to that system.

Adding the CVE id assigned to this vulnerability

---

content/docs/topics/charts.md

Added all the fields to the `dependencies` item of the `Chart.yaml` file
and an example using repository alias instead the repository URL
Signed-off-by: Carlos Juan Gómez Peñalver <carlosjuangp@gmail.com>

Dependency repo alias explained

---

content/docs/faq.md
content/docs/topics/chart_repository.md

remove "helm serve" content and refer to ChartMuseum instead

---

content/docs/chart_template_guide/_index.md
content/docs/chart_template_guide/accessing_files.md
content/docs/chart_template_guide/builtin_objects.md
content/docs/chart_template_guide/control_structures.md
content/docs/chart_template_guide/data_types.md
content/docs/chart_template_guide/debugging.md
content/docs/chart_template_guide/functions_and_pipelines.md
content/docs/chart_template_guide/getting_started.md
content/docs/chart_template_guide/helm_ignore_file.md
content/docs/chart_template_guide/named_templates.md
content/docs/chart_template_guide/notes_files.md
content/docs/chart_template_guide/subcharts_and_globals.md
content/docs/chart_template_guide/values_files.md
content/docs/chart_template_guide/variables.md
content/docs/chart_template_guide/wrapping_up.md
content/docs/chart_template_guide/yaml_techniques.md

In this PR I've added weight to the `chart_template_guide` section of the docs, to restore the correct sort order as per the v2 docs:
Fixes #434.
---
Notes:
* **Regrouping Section** - when the v3 docs [were reorganized](https://github.com/helm/helm-www/commit/7f4422d8f13f57f3f27fd612f3c3c24f597f59ee#diff-1c03d9f049788a11e0339e13c7146d6b) into `intro` and `topics` subfolders, somehow the Chart Template Guide files were spread across these different directories and any navigational flow was lost. Here I have regrouped them as best I can.
* **Menu Label** - I changed _Developing Templates_ to _Chart Template Guide_ to better match the content therein.
* **Missing Files!** - the **[.helmignore File](https://v2.helm.sh/docs/chart_template_guide/#the-helmignore-file)** and **[Next …

[docs] Resort and reorganize the chart_template_guide

---

content/docs/topics/charts.md

Updated the link that directs explicitly to the version 2 of the SemVer spec.
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

Semver 2 link updated

---

content/docs/intro/install.md

These flags make it easier to detect if there is an error downloading
the get_helm.sh script.
Signed-off-by: Craig Rodrigues <craig@portworx.com>

Specify more flags to curl

---

OWNERS

The [`OWNERS.md`](https://github.com/helm/helm-www/blob/master/OWNERS) was shaped around managing the blog and tweaking the website - that is insufficient now that the documentation has moved to this repo from `helm/helm`. 
This PR queue now requires more technical review from the core team, so here I'm adding [maintainers](https://github.com/helm/helm/blob/master/OWNERS) who have been recently active in editing the docs - @jdolitsky @thomastaylor312 @technosophos.

suggest expanding OWNERS

---

content/docs/topics/charts.md

In the docs it is made clear what values are allowed for kubeVersion and how the field is handled by Helm when installing a chart.
Closes [#6343](https://github.com/helm/helm/issues/6343) in helm repo.
Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>

docs: add kubeVersion to Chart.yaml docs.

---

content/docs/faq.md

This patch fixes a broken url Built-in Objects in the FAQ

Broken URL for built-in objects in faq.md

---

config.toml
content/en/docs/chart_template_guide/wrapping_up.md

Preview of fixed links [here](https://5e2898b7297c4f0008ddfa8c--helm-merge.netlify.com/docs/chart_template_guide/wrapping_up/).
Closes #473 and [#7454](https://github.com/helm/helm/issues/7454)

fix broken links on wrapping_up

---

content/en/docs/chart_template_guide/values_files.md

more may be added as time goes on, so we should remove this from the documentation to prevent updating the value.
follow-up from #437

remove numerical value for top-level objects

---

content/en/docs/intro/using_helm.md

This PR fixes the documentation regarding the usage of the `--timeout` flag.
Using `--timeout` without a time unit results in error in helm 3.
Somehow related with https://github.com/helm/helm/issues/7375

Fix --timeout flag

---

content/en/docs/topics/registries.md

Just saw this while reading through the docs.

Fix "enironment" typo

---

CONTRIBUTING.md
content/en/blog/2018-12-11-helm-hub.md
content/en/blog/2019-06-10-get-helm-sh.md
content/en/docs/community/related.md
content/en/docs/topics/chart_repository.md
content/en/docs/topics/plugins.md
themes/helm/layouts/index.html
themes/helm/layouts/partials/nav.html

Just a few minor typo fixes: `Github` -> `GitHub`.

Fix GitHub spelling

---

content/en/docs/topics/provenance.md

I was confused by this piece of documentation because I thought `helm signing key` meant "the fingerprint of the desired key". However, [that doesn't work](https://github.com/helm/helm/issues/7631).

docs(helm): Clarify GPG key selection for `package --sign`

---

.gitignore
.htmltest.yml
Makefile
netlify.toml
themes/helm/layouts/_default/_markup/render-link.html

This PR does a few things:
1. Adds link checking, provided by [htmltest](https://github.com/wjdp/htmltest), to the site build
2. Adds a Hugo [render hook](https://gohugo.io/getting-started/configuration-markup/#render-hook-templates) for links in Markdown files. This hook will automatically convert Markdown links à la `/foo/bar.md` into `/foo/bar`, so we won't need to convert these anymore. In fact, if someone wants to convert those *back* to Markdown links, go for it.
3. Puts all of the site's build logic into a `Makefile`.
This will resolve issues like the one addressed in #501.

Add link checker to site build

---

config.toml
content/en/docs/topics/charts.md
themes/helm/assets/sass/docs-content.scss

Code blocks on the site are having style issues, due to differences in the version of Hugo being used between local dev and  production. More recent version of Hugo apply code syntax highlighting to all blocks during the site build, which is causing conflicts with the site stylesheet.
Example:
This PR cleans up the conflict in styles, and adds [config options](https://gohugo.io/getting-started/configuration-markup#highlight) to specify a light [code theme](https://xyproto.github.io/splash/docs/manni.html) which will suit the site.
With the changes:
---
Closes #499 and #205

[#499] [#522] fix code block styling issues

---

content/en/docs/topics/plugins.md

To clarify that global flags are not passed to the plugin, I've listed them all in the plugins documentation

List all global flags

---

content/en/docs/intro/install.md

This note was recommended when discussing the addition of tests for s390x platform (https://github.com/helm/helm/pull/7096).
It was decided at the meeting that Helm community would continue to accommodate builds  for different platforms and allow tests for those platforms but would be performing automated tests for the Linux AMD64 platform only (as previously). The responsibility however for the testing and validation of Helm for the other platforms is the responsibility of the community which requests Helm for that platform.

Add note about tested release

---

content/en/docs/community/release_checklist.md

When Helm issue #7567 was fixed the sha256sum file existed in place
of the sha256 file. The .sha256 file is being kept for backwards
compat for v3.
This change updates the docs to the new location

Updated the checklist sha245sum url

---

content/en/docs/community/release_checklist.md

Now that we can automatically generate release notes we should tell people to do so.
see https://github.com/helm/helm/pull/7636
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

Add doc for `make release-notes`

---

themes/helm/assets/js/app.js
themes/helm/assets/sass/docs-content.scss
themes/helm/layouts/partials/js.html

* re-enables the doc search _(I had accidentally disabled it whilst rewriting the site theme 🤦🏻‍♂️)_
* re-enables the title urls, for deep linking:
---
Closes #539.

[#539] restore search on docs

---

content/en/docs/chart_best_practices/_index.md
content/en/docs/chart_best_practices/conventions.md
content/en/docs/chart_best_practices/custom_resource_definitions.md
content/en/docs/chart_best_practices/dependencies.md
content/en/docs/chart_best_practices/labels.md
content/en/docs/chart_best_practices/pods.md
content/en/docs/chart_best_practices/rbac.md
content/en/docs/chart_best_practices/templates.md
content/en/docs/chart_best_practices/values.md
content/en/docs/faq/_index.md
content/en/docs/glossary/_index.md
themes/helm/layouts/partials/sidebar.html

This PR fixes #524. Thanks @hickeyma for spotting that glitch.
---
This issue is resolved by changing the range of content shown in the left sidebar.
In changing how the sidebar is generated, the _Chart Best Practices_ section disappeared from the menu, as it sat as a child of the Topics directory. To restore it to the side menu, I moved this directory to the docs root, and added aliases to redirect anyone who uses the prior url structure.

[#524] fix left nav duplicated links

---

content/en/docs/community/developers.md
content/en/docs/intro/install.md

* Removing the listing for Dep as it is no longer used to manage
dependencies
* Updated the compile from source directions as the GOPATH is
no longer needed to install Helm

Updating the developer and source docs

---

content/en/docs/intro/install.md
themes/helm/layouts/index.html

Helm is available as a snap - https://snapcraft.io/helm; added this to the installation options.
Also, this PR is an addition to https://github.com/helm/helm/pull/7827
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

Snapcraft installation instructions added

---

content/en/docs/chart_best_practices/custom_resource_definitions.md

Add explanation about --dry-run flag not supported when CRDs in a chart.
Related: https://github.com/helm/helm/issues/7449

feat(chart_best_practices): Add details about --dry-run with CRDs

---

content/en/docs/howto/charts_tips_and_tricks.md

When a user searches for `"helm.sh/resource-policy": keep` in the helm docs site to know more about it, they will most likely end up on this snippet. It would be good to clarify what the keep resource policy does.

Clarify what the keep resource policy does

---

content/en/docs/community/related.md

Many of the articles listed on the site were written back in 2016. Any projects that haven't seen any activity since 2018 were removed from the list, and some projects have shifted around, so their links were updated to their new homes.
supercedes #547

fix(docs): remove stale related documentation/projects

---

content/en/docs/topics/advanced.md
content/en/docs/topics/architecture.md
content/en/docs/topics/chart_repository.md
content/en/docs/topics/chart_tests.md
content/en/docs/topics/charts.md
content/en/docs/topics/charts_hooks.md
content/en/docs/topics/kubernetes_distros.md
content/en/docs/topics/library_charts.md
content/en/docs/topics/plugins.md
content/en/docs/topics/provenance.md
content/en/docs/topics/rbac.md
content/en/docs/topics/registries.md
content/en/docs/topics/v2_v3_migration.md

The topics were in no particular order. Sometimes this did not
flow well. For example, the sections on chart hooks and chart
tests came before the material on charts.
This change specifies an order to the documents which shows up
in the navigation.

Specifies the order of the topics

---

content/en/docs/topics/charts.md

On hubs, like the Helm Hub, there are charts that do not display
content and the authors are unsure of why. Hubs pull that info
from README files. This has not been explicitly stated thus far.
Adding to the docs to make people aware

Noting that README is displaed on hubs

---

content/en/docs/chart_template_guide/functions_and_pipelines.md

While it's shown a little further below, this adds an explicit example for cluster-scoped resources to the table.

feat(docs): add more `lookup` examples

---

content/en/docs/topics/plugins.md

The `home` command was removed in helm v3.
This commit also updates the location of the plugin directory to
`$XDG_DATA_HOME/helm/plugins` which is the location the helm CLI lists
as the default path:
```
$ helm --help
[...]
Helm stores configuration based on the XDG base directory specification, so
- cached files are stored in $XDG_CACHE_HOME/helm
- configuration is stored in $XDG_CONFIG_HOME/helm
- data is stored in $XDG_DATA_HOME/helm
[...]
```

Remove reference to `helm home` command on plugins page

---

content/en/docs/topics/charts.md

Two chart documentation files...
1. Removing the `GetString` function which does not exist
2. Documenting `annotations` which can be listed in a `Chart.yaml` file

Chart doc fixes

---

config.toml

The documentation of command line arguments often inclucde `--` double
dashes. If the typographer extension is enabled this dashes are replaced
by an 'em dash'. This leads to copy/paste errors from the doc to the
desired script/console.
E.g.
`--set-files foobar` will be converted to `—set-files foobar`

Disable typographer extension in markup parsing

---

config.toml

I think the most sustainable path forward for https://github.com/helm/helm-www/issues/497 (in terms of what we can realistically accomplish right now) is "most current v2 docs" and "most current v3 docs". Trying to maintain docs pinned to minor versions does not look like it is going to happen.

Clarify available doc versions

---

content/en/docs/topics/kubernetes_apis.md

Provide documentation around Kubernetes APIs and  deprecation. The doc will be helpful to Helm users and chart maintainers considering issues that can occur when upgrading to new Kubernetes version, for example https://github.com/helm/helm/issues/7219.

feat(topics): Add doc on Kubernetes APIs

---

content/en/docs/topics/advanced.md

The main issue when storing Helm release information in configmaps,
is that configmaps are typically broadly readable, while secrets are not.
I tried to add language to clarify that. I deliberately removed the mention
to base64, since a candid reader might have incorrectly assumed that
base64 gives a layer of protection.
Feel free to adapt/reject if this doesn't reflect the initial intent of the doc <3

Clarify risks of using configmap backend

---

content/en/docs/helm/helm_template.md

Updating docs to include `--include-crds` flag that was added as part of https://github.com/helm/helm/pull/7138

Add include crd flag to options

---

content/en/docs/topics/advanced.md

Previously the url included the comma, resulting in an invalid url `https://pkg.go.dev/helm.sh/helm/v3,`
This is the rendered html from the website
```html
<p>Helm 3 debuted a completely restructured Go SDK for a better experience when
building software and tools that leverage Helm. Full documentation can be found
at <a href="https://pkg.go.dev/helm.sh/helm/v3,">https://pkg.go.dev/helm.sh/helm/v3,</a> but a brief overview of some of the most
common packages and a simple example follow below.</p>
```

Fix invalid url to go sdk

---

content/en/docs/chart_best_practices/dependencies.md
content/en/docs/topics/registries.md

This adds documentation for the feature added in https://github.com/helm/helm/pull/7613

add documentation about OCI dependencies

---

content/en/docs/topics/charts.md

- Changed `input-values` to `import-values` to match the example in the YAML file.

Change `input-values` to `import-values`

---

content/en/docs/chart_template_guide/functions_and_pipelines.md

As suggested in #635 I tried to detail out the behavior of the lookup function during a --dry-run (or helm template).
Please feel free to add or change.
Best regards,
Alessandro

Specify behavior of lookup function during --dry-run

---

content/en/docs/helm/helm_delete.md
content/en/docs/helm/helm_inspect.md

Some older v2 commands have been deleted and/or renamed, and the CLI docs were causing confusion... @bacongobbler has cleaned this up in #485 👏👏👏 
This PR is a follow-up to add some deprecation notes to the docs.
---
`helm inspect` is now `helm show` and `helm delete` is `helm uninstall`.
These commands see a fair amount of search activity. We could add Hugo Aliases or to the Netlify config to simply redirect the user to the new command, but I think it's worthwhile to clarify the change that took place, even if it takes the user one more click to get to the result. 
_Example stub page._
Note these _"stub"_ doc pages for the old commands are **excluded from appearing in the main left menu**, they are accessible only via searching or directly typing out the old command url. We don't want to …

add notes for depricated commands

---

content/en/docs/community/related.md

Hi,
as in https://github.com/helm/helm-www/pull/567 mentioned correctly the helm-secrets project gets inactive.
helm-secrets is a great plugin because with you want to store secret in an encrypted format. encryption on rest is default compliance rule in a lot of companies in germany.
Since is this mandatory for us I will continue to maintain it.
URL to project: https://github.com/jkroepke/helm-secrets

Add helm-secrets

---

content/en/docs/chart_template_guide/getting_started.md

The explanation tells the reader what they will see in the generated YAML. So I think it would be more clear to first show the output of the `helm get manifest` command, and then give an explanation of what the reader is looking at.

Moving explanation to where it makes sense.

---

content/en/docs/community/release_checklist.md

As part of https://github.com/helm/helm/pull/7005, @bacongobbler requested that I also update the release checklist to include the tests, as to avoid breaking tests on the next release.
The list of test files to update I retrieved from [the last commit that changed the version](https://github.com/helm/helm/commit/8316a403ed16c76c35ce673e163c0ee30b1e8871), plus the test I was adding in my other pr.
Let me know if the wording can be improved, or if I missed any other steps.

Add list of tests to update as part of releasing a new version

---

config.toml
i18n/en.toml
i18n/ko.toml
themes/helm/assets/sass/docs-topbar.scss
themes/helm/layouts/partials/nav-fixed.html
themes/helm/layouts/partials/nav.html

* show the language switcher on all pages
* link directly to the translated page (rather than homepage)
* conditionally hide links when translations do not exist
* include a prompt to encourage further translation
Closes #687.

improve language switching

---

config.toml
gulpfile.js

Updates the how gulp task adapts urls in the helm commands section of the v2 docs.
Fixes #316

[v2] update gulp task to fix hyphens in environment variables

---

content/en/docs/topics/charts.md

Adds an alias to redirect from https://helm.sh/docs/developing_charts/ to https://helm.sh/docs/topics/charts/
---
Fixes #658.

Add chart alias

---

config.toml

Release https://github.com/helm/helm/releases/tag/v2.16.9

Updating v2 in docs

---

content/en/docs/_index.md

Fixes #512 
Instead of adding a long "what is helm" section to the helm docs, I link to the front page of the site (which has a short explanation) and the CNCF project journey (which has a much longer and more detailed explanation).
Tagging @mattfarina for review as he commented on the issue I am attempting to resolve.

Adding helm description and links

---

themes/helm/layouts/partials/nav-fixed.html
themes/helm/layouts/partials/nav.html

There is a difference between building a preview/serging localling
and deploying to production. Building a preview uses make build-preview
which has different options from the make build used for produciton.
Something in the hugo options ended up changing the handling of URLs.
The preview step works the same as `hugo serve` making it difficult
to notice in dev.
The issue here was that external URLs were passed through the
relLangURL template function. This is only to be used for relative
URLs. In some modes it was passing through the full URL and in others
it was taking the path, internationalizing it, and passing that along.
When it mangled the full URL we had the issue.
Since these URLs are for full URLs where we want the full thing passed
through, this change removes the use of …

Fixing navigation greating links that go to nowhere

---

themes/helm/assets/sass/docs-content.scss
themes/helm/layouts/docs/single.html

Adds auto-populated links to the end of each docs page:
---
Closes #553.

[#553] add prev and next links to docs

---

netlify.toml

The previous commit to add a page-level redirect ([here](https://github.com/helm/helm-www/blame/master/content/en/docs/topics/charts.md#L4L7)) did not resolve the issue. 
Adding a proxy redirect to the netlify config to fix #658.

[#658] add netlify redirect for developing_charts

---

content/en/docs/faq/_index.md
content/en/docs/intro/install.md

refs https://github.com/helm/helm/issues/7003
This points Debian/Ubuntu users of Helm to a native repo that makes it easy to install and upgrade Helm.
Signed-off-by: Matthew Fox <matt@getbalto.com>

Add Apt (Deb/Ubuntu) installation instructions

---

content/en/docs/faq/_index.md
content/en/docs/intro/install.md

This separates official channels from non-trusted 3rd parties along
with changing "Kubernetes community" to "Helm community"

Update the install instructions for Helm

---

content/en/docs/chart_template_guide/getting_started.md
content/ko/docs/chart_template_guide/getting_started.md

Fixes https://github.com/helm/helm-www/issues/443
The text in this guide introduces potential confusion by ambiguously implying that all commands are run from the `mychart` directory, which they are not. In this PR, I attempt to clear up that confusion.

Clarify path for template directory

---

content/en/docs/community/release_checklist.md

1. Adding step to push the release branch for patch releases. Not
doing this has caused some issues with follow-up releases
recently.
2. exporting an environment variable. We are doing this step so
it should be documented.
closes #674

Fixing the release checklist

---

content/en/docs/helm/helm_init.md

I noticed the issue #726, seeking clarification around `helm init`. There still seems to be frequent confusion around Tiller (see search data below).
This PR adds a _stub_ page explaining the depreciation, so if someone searches for `init` or `tiller` they will see this note rather than find nothing.

[#726] add a note about helm init

---

netlify.toml

This takes advantage of [Netlify's redirects](https://docs.netlify.com/routing/redirects/) to [rewrite](https://docs.netlify.com/routing/redirects/rewrites-proxies/) requests so that the go metadata appears on any page under the /helm/v2 or /helm/v3 paths.
Fixes: https://github.com/helm/helm/issues/7195
Fixes: #721

Provide go package lookup metadata for individual packages

---

content/ko/docs/chart_best_practices/conventions.md
content/ko/docs/chart_best_practices/custom_resource_definitions.md
content/ko/docs/chart_best_practices/dependencies.md
content/ko/docs/chart_best_practices/labels.md
content/ko/docs/chart_best_practices/pods.md
content/ko/docs/chart_best_practices/rbac.md
content/ko/docs/chart_best_practices/templates.md
content/ko/docs/chart_best_practices/values.md
content/ko/docs/chart_template_guide/getting_started.md
content/ko/docs/community/history.md
content/ko/docs/intro/install.md
content/ko/docs/intro/quickstart.md
content/ko/docs/topics/architecture.md

The aliases should point to the en docs for legacy purposes. Having
them in the ko docs as well is overriding the pointers to the en
docs

Removing aliases to ko docs

---

content/en/docs/topics/permissions_sql_storage_backend.md

As discussed in https://github.com/helm/helm/pull/7635 this PR aims to add documentation about the to-be migrated SQL backend that used to be present in Helm 2. I'm not a native speaker of English so please be forgiving for my mistakes :)

Add permissions management doc for SQL storage backend

---

content/en/docs/chart_best_practices/conventions.md

As noted in issue [#8012](https://github.com/helm/helm/issues/8012), the
ValidName regex have been incorrect for a while. While one could not
install charts with uppercase letters in the names, one did not get a
lint warning. I believe that is fixed since
[PR #8013](https://github.com/helm/helm/pull/8013).
This change clarifies that in the documentation.
I'm not quite certain if the PR fixes other cases too, and if that too should be clarified in the documentation. I hope someone can help me make sure the docs do describe the naming scheme correctly now.

Clarify valid chart naming scheme

---

content/en/docs/topics/architecture.md
content/en/docs/topics/charts.md

A few instances of "Kubernetes Helm" (an older name for the initial release of Helm v2) still existed in the Helm docs.
In this PR, I remove/rephrase them for the era of Helm v3 and beyond.

rephrasing uses of "Kubernetes Helm" in docs

---

content/en/docs/chart_best_practices/dependencies.md
content/en/docs/topics/registries.md

Revert the changes made in #623 regarding features related to OCI dependency charts that have not yet been merged.

Revert unmerged OCI dependency changes

---

content/en/docs/chart_template_guide/builtin_objects.md
content/en/docs/chart_template_guide/getting_started.md

Single space added in the template directive to maintain consistency in the documentation.
`{{.Release.Name }}`  -> `{{ .Release.Name }}` 
Link added for "Accessing Files"

Minor formatting fix

---

content/en/docs/topics/kubernetes_distros.md

Add Amazon AWS Elastic Kubernetes Service (EKS) to the list, with link to Amazon EKS documentation titled "Using Helm with Amazon EKS".
Signed-off-by: Bryan Dady <bryan@dady.us>

Add Amazon EKS to helm docs topics kubernetes_distros

---

content/en/docs/chart_template_guide/builtin_objects.md

Align all template directive names to full `{{ .SomeParent.SomeChild }}`

Change template directive names to complete names to align with others

---

content/en/docs/topics/charts.md

Caret ranges should allow **_minor_** changes instead of major.

Fix caret ranges description

---

content/en/docs/intro/install.md

A small update to the location of the public key for the Debian repo. Now it's served from the same CDN as the indexes and packages, for speed and reliability.
The key is still available at the old location.
Signed-off-by: Matthew Fox <matt@getbalto.com>

Update Debian repo signing key location

---

config.toml
content/en/docs/topics/version_skew.md

With the 3.3.0 release we have a couple of places to update the docs.
(I believe someone with write access to helm/helm should also close out https://github.com/helm/helm/milestone/89.)

updates for the 3.3.0 release

---

content/ja/docs/chart_best_practices/_index.md
content/ja/docs/chart_template_guide/_index.md
content/ja/docs/intro/_index.md
content/ja/docs/intro/install.md
content/ja/docs/intro/quickstart.md
content/ja/docs/topics/advanced.md
content/ja/docs/topics/architecture.md
content/ja/docs/topics/chart_tests.md

Translations should not have aliases. When that happens they
override the english language aliases.
Closes #773

Removing aliases from ja translation

---

content/en/docs/topics/plugins.md

This is part of our effort to not reference XDG. XDG is only on linux and there are Helm specific variables that should be referenced instead.
Closes #779

Remove XDG references from the plugin docs

---

content/en/docs/intro/quickstart.md

It appears some of the confusion in https://github.com/helm/helm/issues/6964 was caused by the mention of one specific old version of Kubernetes on an intro doc. I remove that accurate but confusing line here, and replace it with a pointer to a clarification about the version skew policy.
Hopefully this will make it more obvious what versions of Kubernetes Helm supports.

Clarify version skew

---

content/en/docs/community/localization.md

Clarifying which files should be added to a translation PR and how `aliases` should not be used.

Adding some clarifications

---

content/code/chartmuseum.md
content/en/code/chartmuseum.md

ChartMuseum has switched to use 'main' as the default branch name (vs. 'master'). This change ensures that Go projects import ChartMuseum Go libraries properly.

Use main branch for chartmuseum go mod

---

content/ja/docs/faq/_index.md

Related #843.
This PR translates section headers and a few short sections of the FAQ page into Japanese. Since this page has not been translated, the link to this page is not shown on the side menu and Japanese users cannot notice the existence of this page now. This should be fixed soon to help users understand Helm 3.
After merged this PR, I'm going to translate the remaining sections one by one with cooperation with other translators under the umbrella issue #843.

Translate docs/faq/ into Japanese

---

content/en/docs/chart_template_guide/functions_and_pipelines.md

The lookup docs noted that it returned nil when not connected to
a cluster. This is not true. Instead, an empty map/dict is returned.
This change corrects the docs.
Closes #863

Fixed docs on lookup function

---

config.toml

While going through the release check-list I noticed the version in `config.toml` wasn't up to date.
I don't know what impact that has, but here is the fix.

Bump version for 3.3.4

---

content/en/docs/topics/kubernetes_distros.md
content/ko/docs/topics/kubernetes_distros.md

By default MicroK8s installs older version of Helm. Version 3 available in addon `helm3` (added on 10 January 2020 in pull request https://github.com/ubuntu/microk8s/pull/882).
MicroK8s (v1.19.2) example help output:
```
$ snap info microk8s | grep installed
installed:          v1.19.2                    (1710) 214MB classic
$ microk8s.enable --help
Usage: microk8s enable ADDON...
Enable one or more ADDON included with microk8s
Example: microk8s enable dns storage
Available Addons:
...
helm                 # Helm 2 - the package manager for Kubernetes
helm3                # Helm 3 - Kubernetes package manager
...
```

Fix command for enabling Helm v3 in MicroK8s

---

content/en/docs/chart_template_guide/helm_ignore_file.md

Also adding the notable differences to how .gitignore files are handled.
Signed-off-by: Dirk Mueller <dirk@dmllr.de>
Signed-off-by: Dirk Mueller <dmueller@suse.com>

extend helmignore description examples

---

content/en/docs/chart_template_guide/function_list.md

A really small PR: fix typo, from `funciton` &rarr; `function`.

Fix typo in function_list.md

---

content/en/docs/faq/_index.md
content/en/docs/intro/quickstart.md
content/en/docs/intro/using_helm.md
content/en/docs/topics/library_charts.md
content/ja/docs/faq/_index.md
content/ja/docs/intro/quickstart.md
content/ja/docs/intro/using_helm.md
content/ko/docs/faq/_index.md
content/ko/docs/intro/quickstart.md
content/ko/docs/intro/using_helm.md
content/ko/docs/topics/library_charts.md
content/zh/docs/faq/_index.md
content/zh/docs/intro/quickstart.md

Update old Google URLs to new helm.sh URLs.
This change should be merged on October 19, 2020

update repository URLs

---

config.toml
content/en/docs/community/release_checklist.md
content/en/docs/topics/release_policy.md
content/en/docs/topics/version_skew.md
i18n/en.toml
themes/helm/layouts/index.html

The following is a suggestion of how we could publish the next release's date.  But I don't know the site that well, so feel free to suggest a more appropriate location.
A new "Next Feature Release" section is added on the main page under the "Community" section.
The Release Checklist is also updated.
Japanese, Chinese and Korean will be shown in English until translated.
The next release is marked to be `3.5.0` for `January 13th, 2021` as suggest in the HIP review.
This PR, if approved, should only be merged once `helm 3.4.0` has been released.
This is what the new section would look like (notice the top left box):

Add next release date as per HIP 0002

---

content/en/docs/topics/version_skew.md

_What is this PR for?_
When Helm starts supporting k8s 1.19 as noted in https://github.com/helm/helm/pull/8807, we should note that in the version skew doc: https://helm.sh/docs/topics/version_skew/
_When do we merge this?_
This should be merged after the release of 3.4.0.

Update supported versions

---

content/en/blog/2020-10-30-charts-repo-deprecation.md

Adding blog to info out about the Chart repos deprecation timeline and recommended actions that users need to take.

Add Charts repo deprecation blog

---

README.md

I thought it may be of value to mention that when generating the helm docs, the specific helm version should be used.
For instance, my version helm is often point to the latest master, which would not represent the exact commands that need to be generated for a specific version.

Mention to run proper version to generate docs

---

content/en/docs/chart_best_practices/templates.md
content/en/docs/topics/library_charts.md
content/ko/docs/chart_best_practices/templates.md
content/ko/docs/topics/library_charts.md

- The comment examples previosly shown are unusable because they produce
this error:
"error converting YAML to JSON: yaml: line X: did not find expected key"
- See also https://github.com/helm/helm/issues/4191
Signed-off-by: Shannon Carey <rehevkor5@gmail.com>

Fix invalid examples of Helm template comments

---

netlify.toml

Helm adopted a release schedule and there is now a release
calendar. This provides a redirect to the calendar.

Adding release calendar redirect

---

content/en/docs/intro/using_helm.md

There is a mismatch between the definition of the unit measure for the `--timeout` parameter and its example.

update inconsistent timeout definition

---

content/en/docs/community/related.md

[`helm-git`](https://github.com/aslafy-z/helm-git) is a Helm downloader plugin that retrieves charts from Git repositories and package them on the fly. It has support for Helm 2 and 3 and will soon allow pulling values files ([aslafy-z/helm-git#120](https://togithub.com/aslafy-z/helm-git/pull/120)).

Add helm-git as related project

---

content/en/docs/community/release_checklist.md
content/en/docs/topics/release_policy.md
i18n/en.toml
themes/helm/layouts/index.html

This PR:
* adds the link to the release calendar on the main page (see image below)
* adds instructions to update the calendar in the release check-list
* adds the link to the release calendar in the release schedule policy
Suggestions on formatting welcomed.

Add mentions of release calendar

---

content/en/docs/topics/registries.md

👋🏻 Hi there! 
I personally found the [Registries ](https://helm.sh/docs/topics/registries/) page on my own and found it very helpful, but ended up shying a way a bit when I found out it was still an experimental feature. There wasn't much there that explained why that was and the OCI HIP was in the community repo. I think it prudent to add a link to the OCI HIP in helm/community to lead folks there for more info.

Add link to OCI HIP from Registries page

---

README.md

To generate helm command documentation, the new `--generate-headers` flag allows to avoid having to add the headers back by hand.  See https://github.com/helm/helm/pull/8961
This PR updates the doc that explains how to generate that documentation.
This new flag will be part of helm 3.5.  So we may want to wait until it is release to merge this.  However, I'm not sure the docs will need to be regenerated for helm 3.4.1 or 3.4.2, so it may be ok to merge this change now, I'm not sure.

Update README to use new --generate-headers

---

content/en/docs/community/related.md

Adds 2 references: 
* helm-tanka plugin to consume Tanka/Jsonnet with Helm
* Tanka, which can consume Helm Charts

docs: refer to Tanka and the helm-tanka plugin

---

content/en/docs/community/developers.md

* Golangci-lint is needed for running all tests.
We can update the docs after https://github.com/helm/helm/pull/7695 is merged.

docs: Add pre-req for running tests

---

content/en/docs/topics/registries.md

Document how to specify dependencies in Chart.yaml so that depencency update can pull them.
This resolves a confusion I had in https://github.com/helm/helm/issues/9267.

Document dependencies from OCI registry

---

content/en/docs/topics/charts.md
content/en/docs/topics/library_charts.md
content/en/docs/topics/provenance.md

Updated doc references to appVersion to reflect recommendation of quote-wrapped version.
This change took affect in Helm v3.5.0.
For context, refer to: 
- https://github.com/helm/helm/issues/9083
- https://github.com/helm/helm/pull/9084

Update references to appVersion

---

content/en/docs/topics/release_policy.md

We have settled on a cancellation policy for patch releases now detailed in [HIP 0002](https://github.com/helm/community/blob/master/hips/hip-0002.md#cancelling-a-patch-release).
The discussion was concluded [here](https://github.com/helm/community/issues/160#issuecomment-761586180)
This PR adds the cancellation details to the web page so that it can be easily found by the community.

Add patch release cancellation conditions

---

content/en/docs/chart_template_guide/builtin_objects.md
content/en/docs/chart_template_guide/wrapping_up.md
content/en/docs/community/release_checklist.md
content/en/docs/howto/charts_tips_and_tricks.md
content/en/docs/intro/quickstart.md
content/en/docs/intro/using_helm.md
content/en/docs/topics/chart_repository.md
content/en/docs/topics/charts.md
content/en/docs/topics/library_charts.md
content/en/docs/topics/provenance.md

Adjustments to docs to reflect the following changes:
- Artifact Hub, not the helm/charts repo, is where people can find charts
- There is not an active "Kubernetes Charts" project
- client-side SSL is not a work in progress anymore
There is not a new location for "common helm helper chart" and it's listed as deprecated, so that section needs overhaul, but I made a minimal change to acknowledge that it's not currently the recommendation.
While many other improvements are warranted, this is fairly low-hanging fruit to get in so the docs are more correct.

Adjust docs to reflect Artifact Hub & helm/charts updates

---

content/en/docs/chart_template_guide/getting_started.md

The word "container" in this context might lead to the misunderstanding that ConfigMaps create containers/pods.

Improve wording

---

content/en/docs/chart_template_guide/values_files.md
content/ko/docs/chart_template_guide/values_files.md
content/zh/docs/chart_template_guide/values_files.md

Template output is wrong.
A different value is used from the release name passed as a command line parameter.

Fix console output

---

themes/helm/assets/js/foundation.js

This fixes an issue that prevents the menu from expanding on Chrome and Edge, reading the issue discussion it sounds like there is a goal to move away from this menu code and I'd agree that is the best long term solution. Currently it's pretty bad rendering, however this bug makes the menu completely broken on Windows Chrome & Edge and I think should be fixed before waiting for rewrite.
Fixes #914
Here is a gif showing what is broken:
Here are gifs showing it working in all FireFox, Edge, and Chrome on Windows:

Fix menu in Edge and Chrome on Windows

---

content/en/docs/chart_template_guide/subcharts_and_globals.md

`rm -rf mysubchart/templates/*.*` keeps files in tests directory, and subsequent ` helm install --generate-name --dry-run --debug mychart/charts/mysubchart` fails.

Change command to remove all files including tests

---

content/en/docs/topics/version_skew.md

The 3.5.x supported versions were missing.

Add kube supported versions for 3.5

---

i18n/en.toml
i18n/ja.toml
i18n/ko.toml
i18n/ru.toml
i18n/zh.toml
themes/helm/layouts/partials/banner.html

Note, the template has been updated so that the banner is optional
and the region only displays if a banner is present.
The banner was discussed among some org maintainers and then taken
to the org maintainers list. This change is after the normal lazy
concensus period and there was no disucssion.
Taking down the banner was raised as a question about when should
something like this happen? Is it when the problem is solved, when
another issue comes along to replace it, or some other time?
Given that other projects (e.g., Kubernetes) have removed their
banner and that Helm is not a political or activist organization
(so we don't see a next replacement banner along these lines)
now appears to be a reasonable time to remove it.
It is worth noting that the Helm community is a global community. …

Removing current banner that has been up for past 9 months

---

content/en/docs/community/developers.md

Clarifying where CLI docs are edited, based on feedback in https://github.com/helm/helm-www/pull/1069#issuecomment-819933254.

Clarifying where CLI docs are edited.

---

config.toml
themes/helm/assets/sass/docs-topbar.scss
themes/helm/assets/sass/helm-home.scss
themes/helm/assets/sass/helm-layout.scss
themes/helm/layouts/partials/nav-fixed.html
themes/helm/layouts/partials/nav.html

This PR adjusts the CSS for the top menu bar as follows:
* restores the correct spacing following banner removal (#1054)
* makes use of the active class to highlight current language
In addition, this PR changes the way the languages menu is populated, sorting them in order of the language code (`en`, `ko`, `zh` etc) and removes the English language word for each language from the title.
---
Current menu screenshot:
Proposed change screenshot:

Language Menu Adjustments 

---

content/zh/docs/chart_template_guide/subcharts_and_globals.md

The meaning of these two sentences is reversed；
覆盖父chart中的值---->Parent Chart is overwritten.
顶层的值已经被子chart的值覆盖了---->
The Parent Chart is covered by the SubChart.

fix Chinese translation

---

content/en/docs/howto/charts_tips_and_tricks.md

It is confusing to see a variable reference without backticks around it, especially when the first `.` can be misinterpreted as an end of sentence.
I had an issue with generating the markdown: after running `helm docs --type markdown --generate-headers`, all markdown files that originally referenced `~` were replaced with my actual home directory (`/home/myname`). I don't want to commit that, and I assume you guys don't want me to either, so I've reverted that change. I haven't created a new issue, as https://github.com/helm/helm-www/issues/487 already exists. 
Before:
After:
Signed-off-by: Steven Pitts <makusu2@gmail.com>

Add backticks around .Values.who

---

content/en/docs/intro/quickstart.md

This allows the quickstart guide to not show deprecation messages to the user when following it. The issue was raised in #965.
Using `bitnami` as repo is subject to edits, it seems like the closest to what https://charts.helm.sh/stable was and it is the first Helm-related repository containing charts when using this list: https://github.com/topics/charts?o=desc&s=stars
Translations remain to be done but I believe a first pass should be given to review the repo used.

Update quickstart guide to use non-deprecated repo

---

content/en/docs/community/related.md

lrills/helm-unittest does not seem to be maintained any longer: https://github.com/helm/helm/issues/5424
https://github.com/quintush/helm-unittest/ seems to be currently the most maintained version of the project.
Alternatively we could point people to [Rancher's fork](https://github.com/rancher/helm-unittest).

Link to a maintained fork of helm-unittests

---

content/en/docs/community/related.md

Hello!
This PR adds a new helm plugin called `adopt` to help user to adopt k8s existing resources into a new generated helm chart

add adopt plugin 

---

content/en/docs/howto/charts_tips_and_tricks.md

Hi,
I'm new to using Helm and I really like how the docs guided you towards getting a checksum of a file to control automatically rolling out your deployments if a file changes, such as a config map or secret.
But when I transitioned to using library charts the approach in the docs no longer worked because it seems library charts aren't included in the `$.Template.BasePath` path.
This PR addresses this by adding an example that works with library charts.

Add example on using auto roll deployment checksum with library chart

---

content/en/docs/chart_template_guide/control_structures.md

The configmap manifest in the tutorial was invalid because the value being assigned to mug was boolean and not a string.
This caused issues with helm install without the --dry-run --debug flags because the manifest is invalid.
I have changed the manifest for configmap in the tutorial to use mug: "true" which no longer throws errors.
Signed-off-by: Aahan Singh <aahansingh95@gmail.com>

Fixed invalid configmap manifest in the tutorial.

---

content/en/docs/topics/version_skew.md

3.6.x was missing from the version_skew documentation.
I'm quite certain it is true but I haven't tested it.
I also don't know if there are other docs that needs updating

Add 3.6.x to version_skew doc

---

content/en/docs/topics/charts.md

This topic came up in today's Helm dev call for a completely different reason.
I seemed to remember this note in the docs, which is no longer true - checked, and it's still there. Small update so this is more accurate. For more context, see release notes on https://github.com/helm/helm/releases/tag/v3.3.2.
To cover our bases, I also searched the docs for keywords like `yaml` and `fields`. One question about the note below – it seems to still be accurate, but does anyone know of a reason why we should update this with more detail as well?
>**NOTE:** Any unknown `Chart.yaml` fields will be dropped. They will not be
>accessible inside of the `Chart` object. Thus, `Chart.yaml` cannot be used to
>pass arbitrarily structured data into the template. The values file can be used
>for that, though.

Document stricter YAML parsing

---

themes/helm/assets/sass/docs-sidebar.scss

This PR closes #1032
Change padding in toctree items to effected by viewport, same as [the parent](https://github.com/helm/helm-www/blob/97a09604ba1723834164184786bdde20786a21d8/themes/helm/assets/sass/docs-sidebar.scss#L48).
Image is taken on 3840p (4k)
Before:
After:
Signed-off-by: sugardon <sugar2don@gmail.com>

Change padding in sidebar toctree items

---

OWNERS

As she has been voted in by a supermajority of the current helm-www OWNERS I am adding @angellk to the file here.
Still to do (requires access, and perhaps can be handled by whomever approves this PR):

Adding maintainer

---

content/en/docs/chart_best_practices/dependencies.md

- for when a repo isn't specified
- adding details on downloader plugins
- removing reference to the obsolete official repo

Updating the docs on dependencies

---

content/en/docs/intro/quickstart.md

This PR changes a `helm ls` reference in the Quickstart to `helm list`. The official Helm docs make no references to the `helm ls` command, even though it is currently a valid alias for `helm list`. Additionally, the command used in the terminal snippet now matches the description underneath it, as they now both use `helm list`. 
Signed-off-by: chloe andresol <candreso@gmu.edu>

Fixed command in quickstart.md

---

content/en/docs/topics/chart_repository.md

Adds documentation providing information on using the GitLab Package Registry for Helm Charts.

Add documentation for GitLab Chart Repo

---

content/en/docs/topics/charts.md

This is a follow-up of https://github.com/SchemaStore/schemastore/pull/1815, where I stated my reasonings.

Make `version` optional for dependencies

---

themes/helm/assets/js/app.js
themes/helm/assets/sass/docs-responsive.scss
themes/helm/assets/sass/docs-sidebar.scss
themes/helm/assets/sass/docs-topbar.scss
themes/helm/layouts/partials/nav-i18n.html
themes/helm/layouts/partials/nav-versioning.html
themes/helm/layouts/partials/nav.html
themes/helm/layouts/partials/sidebar.html

This PR replaces #705 which had become rather stale (_a relic really_) - this is a reworking of the CSS that determines the layouts at different screen sizes, changing how navigation, text sizing, etc are tailored to suit mobile users / tablet users / desktop users.
* removes the _Get Started_ menu button on docs pages
* reworks the docs menu to work as a fly-out with a hamburger
* reworks the spacing of the mobile menu across the top
* text sizing and scale adjustments
Addresses #683 #741

Improve site for mobile screens

---

content/en/docs/community/related.md
content/ko/docs/community/related.md
content/zh/docs/community/related.md

Hello,
the helm-gcp project moved from preview owner to me (@hayorov) a year ago or so.
This is a link update PR.
Proof:
```
❯ curl https://github.com/nouney/helm-gcs                     
<html><body>You are being <a href="https://github.com/hayorov/helm-gcs">redirected</a>.</body></html>%    
```

docs(FIX): Update helm-gcs repo link after project migration

---

content/en/docs/chart_template_guide/function_list.md

Hello, I noticed the docs for the `index` function were missing. From my usage of it and the helm/sprig source, I assume it comes from [Go templates](https://pkg.go.dev/text/template#hdr-Functions). Because it doesn't come from Sprig, it looks like there is no `mustIndex`. Thought I'd add it in spirit of this comment from https://github.com/helm/helm-www/issues/489#issuecomment-582958396 , with the main tracking issue being https://github.com/helm/helm-www/issues/706 . I am open to whatever wording changes the maintainers feel would be needed!
> We should not expect so many people to know Go templates and sprig functions.

Docs for template function "index" on lists

---

content/en/docs/chart_template_guide/function_list.md

The docs currently state that the `and` and `or` functions take two arguments, but this isn't true - they are variadic.
I think a similar change is needed in Chinese and Korean, but unfortunately I don't speak either of those languages!

`and` and `or` functions can take many arguments

---

content/en/docs/topics/registries.md

Added a note for `helm push` to OCI registries which may require namespace and/or repository to be created beforehand.
Related to https://github.com/helm/helm/issues/10169

Added note precreating namespace or repository for helm push

---

content/en/docs/chart_best_practices/values.md

This PR corrects a small grammar mistake found here: https://v2.helm.sh/docs/chart_best_practices/#consider-how-users-will-use-your-values .

fix grammar in chart_best_practices/values.md

---

content/en/blog/2022-02-28-storing-charts-in-oci.md

On the site, the formatting of this is a little odd. Remove the `console` annotation to make this plain text
Related to #1284
cc @scottrigby @mattfarina

oci blog post: remove syntax highlighting

---

content/en/docs/intro/install.md

Scoop is another popular package manager for windows, major difference is scoop does not require elevated privileges.
For the other languages, I feel I should add the hyperlink and the scoop commands and allow other contributors to provide correct language changes?

Adding scoop package manager (windows) install instructions

---

.gitignore
netlify.toml
themes/helm/layouts/partials/nav-i18n.html

This was a pretty small edit to resolve the `hugo` build error documented in #1288. 
Here I replace the depricated `.URL` code and the site builds without any issue on the latest Hugo version (v0.94.0 ).

[1288] update site template to work with newer hugo versions

---

content/en/docs/community/related.md

Link to sigstore here is broken due to an empty space https://helm.sh/docs/community/related/

Remove empty space that breaks sigstore link in plugins list

---

content/en/docs/community/related.md

Hey there 👋 
I recently wrote a plugin that allows to fetch values from external sources. Currently it supports fetching values from kubernetes configMaps and secrets  but I'm planning on adding support for more in the future.
I have examples on how to use it with argocd in the Readme.
Adding it here to get more visibility in case the helm community is interested.

Add helm-external-val to the list of helm plugins

---

content/en/docs/topics/chart_tests.md

The current bitnami/wordpress chart does not have
the test file anymore. This was removed in https://github.com/bitnami/charts/commit/8060430325eaaa2faa7ec94671b5b170488313f2
Signed-off-by: Jesper Axelsen <jesperbaxelsen@gmail.com>

docs(helm): update chart_testing.md with new test

---

config.toml

The Helm 3.9 release (and RC1) have been delayed a week to wait for Kubernetes 1.24 as announced here: https://lists.cncf.io/g/cncf-helm/topic/helm_3_9_0_release_date/90835923

Delay 3.9 release to wait for kubernetes 1.24

---

content/en/docs/intro/using_helm.md

resolves https://github.com/helm/helm/issues/10598
tested using:
```bash
$ helm version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
$ minikube version
minikube version: v1.22.0
commit: …
```

add: examples for --set with [] and null in the using_helm docs.

---

content/en/docs/intro/install.md
content/es/docs/intro/install.md
content/fr/docs/intro/install.md
content/ja/docs/intro/install.md
content/pt/docs/intro/install.md
content/ru/docs/intro/install.md
content/zh/docs/intro/install.md

The usage of apt-key is deprecated and creates a warning.
Warning: apt-key is deprecated.
Each gpg key should only be valid for packages in its own repository.
I adapted the documentation according to the [Debian Wiki](https://wiki.debian.org/DebianRepository/UseThirdParty).
Signed-off-by: Raffael Stein <rvs@mailbox.org>

docs(install): Update Apt installation in readme

---

content/en/docs/chart_template_guide/control_structures.md

I have seen (and, in fact, written) plenty of templates that use this behaviour, but couldn't find it documented within helm.
I did, however, find it documented here https://pkg.go.dev/text/template#hdr-Actions.

Docs: explain conditional behaviour of 'with'

---

content/en/docs/topics/charts.md

Fixes the multi-condition example as the syntax `condition1, failoverCondition` is not supported by Helm (it stops evaluating at the space and includes the dependency).
The working syntax is `condition1,failoverCondition`.

Fix multi-conditon example

---

content/en/docs/chart_template_guide/debugging.md

`helm install --dry-run --debug` interacts with kube api server, `helm template --debug` renders the chart locally
Signed-off-by: w7089 <3884662+w7089@users.noreply.github.com>

helm template renders the chart locally

---

content/en/docs/chart_template_guide/control_structures.md
content/ko/docs/chart_template_guide/control_structures.md

I feel like there is a typo in this example :
https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace
This is my first time contributing so I'm not sure about the process to fix it even though I've read the contributing guidelines. 
Let me know if there's anything that need to be done in order to merge this PR.
Signed-off-by: William Le Pommelet <w.lepommelet@gmail.com>

Doc : typo in online documentation

---

content/en/docs/topics/plugins.md

The "name" field of the sample YAML was "last" and should replace "keybase" in the doc as its a typo.
Signed-off-by: Emran BatmanGhelich <emran.bm@gmail.com>

Fix typo in plugin YAML example

---

content/en/docs/chart_template_guide/accessing_files.md
content/en/docs/chart_template_guide/subcharts_and_globals.md
content/en/docs/topics/library_charts.md

Signed-off-by: Miles Wilson <wilson.mil@icloud.com>
In general, there is confusion around the use case for accessing files between subcharts and parent charts, exemplified through https://github.com/helm/helm/issues/1892.
The goal of this commit is to shed more light on the benefits of using library charts. As far as I can tell, these differences are not explicit the official docs, and many people seem to think that there is very little benefit in using library charts beyond extracting code to be used in multiple charts. Through experimentation, I have found the two peices of functionality documented in this commit very useful:
- Accessing the entire .Values dict from the parent chart, not just the slice with the subchart header
- Being able to access the parent chart's files from a …

Added details on library chart differences from application charts

---

content/en/docs/community/related.md

This PR adds Botkube to the community/related page. We've just added a Helm plugin to Botkube that allows users to run Helm commands from their chat platforms.
Signed-off-by: Blair Rampling <brampling@users.noreply.github.com>

Add Botkube to the Community Related page

---

content/en/docs/helm/helm_dependency.md

I recently searched for a solution how to reuse a chart multiple times. Unfortunately the documentation about how to add dependencies had no such information.
I found something about it in the Chart.yml keyword description.
In my opinion this should also be mentioned in the documention about how to add dependencies because this is the first place where people start looking.

Add howto reuse chart multiple times in dependency doc

---

themes/helm/layouts/index.html

In learning what a gofish was, I see that it's now deprecated. Instructions are not in the docs; this commit updates the home page to match.

docs: Remove gofish from index samples

---

content/en/docs/chart_template_guide/function_list.md

Add documentation for `dig` function from Sprig.
The documentation is taken from Sprig's documentation: https://github.com/Masterminds/sprig/blob/master/docs/dicts.md#dig

Add documentation for dig

---

content/en/docs/chart_template_guide/function_list.md

Add a simple example for a better understanding the `merge` function. The values also have been taken from the `mergeOverwrite` example to be compared the results.

add a simple example for merge function

---

content/en/docs/chart_template_guide/yaml_techniques.md
content/ko/docs/chart_template_guide/yaml_techniques.md
content/zh/docs/chart_template_guide/yaml_techniques.md

Some of the Yaml examples spell "Cappucino", others "Cappuccino". [The correct spelling appears to be "Cappuccino".](https://en.wikipedia.org/wiki/Cappuccino) This changes uses that spelling.

Spell "Cappuccino" consistently

---

content/en/docs/intro/CheatSheet.md

**Issue**
There is a typo in the cheat sheet documentation. The command helm list --all and helm list --all-namespaces is written with only a leading single dash.

fix cheat sheet documentation typo in helm list

---

content/en/docs/chart_template_guide/function_list.md

Similar to https://github.com/Masterminds/sprig/blob/master/docs/mathf.md.

Document Float Math functions

---

content/en/docs/intro/CheatSheet.md

Currently cheatsheet doesn't show up in the sidebar navigation and "next" page title shows as empty for "Using Helm" page, hopefully this fixes that issue

Make cheatsheet appear properly on side navigation and next page

---

content/en/docs/community/related.md

Hello,
I wanted to propose a mentioning of this open source project here. 
It is built in form a Helm library chart and has been around for more than two years now. Many tests exist to back every releases stability and it is used in production.  
Not sure if it should better go under the plugins sections but these seem to be (almost) exclusively actual helm plugins there?
Thanks!

Add external project HULL to list

---

content/en/docs/chart_template_guide/function_list.md

Adding a section about the `required` function, that is for now only mentioned in the [tips and tricks](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-required-function) section

add section about the `required` function

---

README.md
config.toml
content/en/docs/_index.md
content/en/docs/chart_template_guide/accessing_files.md
content/en/docs/chart_template_guide/builtin_objects.md
content/en/docs/chart_template_guide/control_structures.md
content/en/docs/chart_template_guide/functions_and_pipelines.md
content/en/docs/chart_template_guide/getting_started.md
content/en/docs/intro/using_helm.md
themes/helm/layouts/partials/footer-links.html

Closes #1526 
Closes #1530 
Fixes #1528 
Fixes #1525 
* Adds a small note that Hugo extended edition is required. GitHub Codespaces, for example, have default runners with regular Hugo installed which will fail when attempting to render the site. Although `brew install hugo` does install the extended edition, this isn't obvious from the command alone.
* Fixes a sentence which appears to be a remnant from Helm v2 days.
* Fixes some broken links
* Updates links from Helm Hub to Artifact Hub
* Minor linting and styling updates

Misc fixes

---

content/en/docs/howto/chart_releaser_action.md
content/es/docs/howto/chart_releaser_action.md
content/zh/docs/howto/chart_releaser_action.md

1. `helm/chart-releaser-action` need write permission to run it correctly otherwise it will report permission error 
2. upgrade `helm/chart-releaser-action` to v1.6.0

fix: add permission to write repo & upgrade action to v1.6.0

---

content/en/docs/intro/using_helm.md

600M lacks the Bytes (presumably)

Add missing B to 600M

---

content/en/docs/chart_best_practices/templates.md

Using `# {{ .Values.undefinedVar }}` in a template can cause unexpected errors for those unfamiliar with the `{{/* */}}` block syntax.

docs(chart_best_practices): callout error with YAML comments

---

content/en/docs/topics/provenance.md
content/en/docs/topics/registries.md

Fixes https://github.com/sigstore/cosign/issues/1118
Related-to https://github.com/helm/helm/issues/11496
It's possible to use (GPG-keyed) signing with Sigstore today, adding cross-links to documentation to make it more discoverable.

Add links to helm-sigstore project

---

content/en/docs/howto/charts_tips_and_tricks.md

Quotation marks around `helm.sh/resource-policy` are not required, and moreover, the usual YAML style is to not include quotes in keys unless necessary.
Remove the quotes and the claim that they are required.
Fixes helm/helm#12555.

charts_tips_and_tricks.md: remove misleading wording about quotes

---

content/en/docs/chart_template_guide/debugging.md

Hi there,
in the [`Debugging Templates`](https://helm.sh/docs/chart_template_guide/debugging/) docs  is a double equal signs in the docs for using `--dry-run=server`.
Only one should be used here.

fix: remove double equal signs

---

content/en/docs/howto/chart_releaser_action.md
content/es/docs/howto/chart_releaser_action.md
content/zh/docs/howto/chart_releaser_action.md

Updated the examples for GitHub Actions to match the latest `actions/checkout` version, cleaning up deprecation messages.
It has the same motivation as https://github.com/helm/helm-www/pull/1432 😄 
I hope it helps!

Update GitHub Actions examples

---

content/en/docs/chart_template_guide/subcharts_and_globals.md

Command resolves to an error, saying 'must either provide a name or specify --generate-name', adding the flags fixes that.
Alternative adding "rude-cardinal" (same name as previous guides) `helm install rude-cardinal --dry-run --debug mychart`

Added --generate-name flag for command

---

content/en/docs/chart_template_guide/function_list.md

Fix #1560 
The function already exists (https://github.com/helm/helm/blob/main/pkg/engine/funcs.go#L50), the documentation is missing though

Add toToml to function list

---

content/en/docs/chart_template_guide/function_list.md

I spotted what appears to be an error in the docs for the casing of the example for `wrapWith`.
What I've changed in this PR is the simplest thing that fixes the documentation issue.
However, I think the example could perhaps be improved, eg:
> ```
> wrapWith 5 "_" "abcdefghijkl"
> ```
>  The above produces `abcde_fghij_kl`.
Perhaps that would make the behaviour of `wrapWith` clearer? If that is wanted, let me know if it should go in this PR or be separate.

Fix error in wrapWith example

---

content/en/docs/topics/charts.md

I added more context for using starters because the current explanation is a little bit confusing.

Added examples for using `Chart Starter Packs` and a few explanations.

---

content/en/docs/chart_template_guide/function_list.md

The "Chart Template Guide > Template Function List > Cryptographic and Security > derivePassword" docs have a broken link.
The algorithm for this is well specified.
I replaced the link to the original PDF on the internet archive: https://web.archive.org/web/20211019121301/https://masterpassword.app/masterpassword-algorithm.pdf
Fixes helm#1589

Update URL in derivePassword docs

---

content/en/blog/2024-06-26-the-road-to-helm-4.md

Road to Helm 4 Blog
cc: @scottrigby @karenhchu

Road to Helm 4 Blog

---

content/en/docs/chart_template_guide/values_files.md

This pull request is about fixing typos and omissions on the values files documentation page.

Docs: Fix typo on the values files page

---

content/en/docs/helm/helm_upgrade.md

update doc to include --hide-secret that is supported in 3.15.3 
https://github.com/helm/helm/commit/25c473834e0cbb905fc8a524709fd4d5362dab11
https://github.com/helm/helm/blob/main/pkg/action/upgrade.go#L79

update helm upgrade doc to include --hide-secret that is supported in 3.15.3

---

content/en/docs/chart_template_guide/function_list.md

```shell
❯ helm version
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}
❯ cat templates/main.yaml
kind: wow
metadata:
name: amazing
data:
int: {{ 1 | duration }}
string: {{ "1" | duration }}
❯ helm template .
---
kind: wow
metadata:
name: amazing
data:
int: 0s
string: 1s
```

make is clear duration expects a string

---

content/zh/docs/chart_template_guide/function_list.md

The "Chart 模板指南 > 模板函数列表 > Cryptographic and Security > derivePassword" docs have a broken link.
The algorithm for this is well-specified.
Since Master Password was rebranded as Spectre in 2021, I replaced the link with the new URL and path.

Replace broken URL in derivePassword zh docs

---

content/en/docs/topics/version_skew.md

I know it's a duplicate of #1613, but since that PR hasn't been able to move for 2 weeks I offer an alternative that can be merged

chore: Update version_skew.md for 3.15.0 release

---

content/en/docs/community/developers.md
content/en/docs/topics/plugins.md

Small doc's update to explain to developers how to test helm and plugins locally.

updating the docs for local testing setup

---

content/en/docs/community/related.md

Aptakube has supported Helm for some time now, and a user recently suggested adding it here.

Add Aptakube to "Related Projects and Documentation"

---

themes/helm/assets/sass/helm-boat.scss

Boats in water don't just rise/sink vertically, their bow and stern dip up/down as they crest the waves of the water. This PR adds a slight rotation to simulate this.

Boat bob rides waves more realistically

---

content/en/docs/chart_template_guide/data_types.md

According to the [go docs](https://pkg.go.dev/fmt)
- %t	the word true or false
- %T	a Go-syntax representation of the type of the value

Fix: typo in data_types.md

---

config.toml
i18n/en.toml

Note, also bumped current Helm version

Adding kubecon NA SLC to upcoming events

---

content/en/docs/intro/install.md

It appears the wording of "stable repo" may have been confusing since installation may come from a repo..
Closes: https://github.com/TerryHowe/helm-www/pull/new/add-chart-repository

fix: clarify that the repo is a chart repository

---

themes/helm/layouts/_default/list.html
themes/helm/layouts/_default/single.html

This change gets rid of this warning:
```
WARN  found no layout file for "html" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

fix: get rid of build warning

---

content/en/code/helm-v4.md

Helm uses custom URLs to get to the code. In this case helm.sh/helm/v4 should point to the main branch for helm so that people who try to use it with go modules are able to.
This change adds that redirect to the default language which means it should work for everyone.

Adding redirect for helm/v4 to the code

---

content/en/docs/community/related.md

https://github.com/pidanou/helm-tui
It's a terminal UI written in GO, the objective is to have a simple way to manage Helm assets without typing all the commands

Add plugin `helm-tui`

---

content/en/docs/chart_template_guide/named_templates.md
content/en/docs/chart_template_guide/variables.md

I just got bitten by the fact that you cannot use the `$` sign to access the root context when using a named template.
This should solve #1399

clarify global scope meaning for named templates

---

content/en/docs/chart_template_guide/accessing_files.md
content/en/docs/chart_template_guide/variables.md

Closes: https://github.com/helm/helm-www/issues/1513

fix: yaml examples with bad doc separator

---

content/code/chartmuseum.md
content/code/helm-v2.md
content/code/helm-v3.md
content/code/helm.md

These redirects removed in this PR are not used. The extra files cause confusion and delay.
These redirects *are* used: https://github.com/helm/helm-www/tree/main/content/en/code
Validate redirects from this PRs preview:
https://deploy-preview-1645--helm-merge.netlify.app/chartmuseum
https://deploy-preview-1645--helm-merge.netlify.app/helm
https://deploy-preview-1645--helm-merge.netlify.app/helm/v2
https://deploy-preview-1645--helm-merge.netlify.app/helm/v3

chore: remove unused redirects to reduce confusion

---

content/en/docs/topics/chart_repository.md

During my Helm booth duty at Kubecon in SLC a user had not considered using a registry to store charts. It seems like that should be more clear as a possibility.

fix: suggest using registry over repository

---

.dockerignore
Dockerfile
Makefile

Resolve: #1591
This PR adds `serve`, `image` and `image-run` targets to the Makefile. This allows you to build and run a container locally with the latest Hugo version to serve the Helm documentation.
Use `make image` to build the container locally. `make image-run [target]` allows you to run specific targets from the Makefile using the container; running `make image-run` is the same as `make image-run serve`, it runs Hugo in the container to serve the documentation locally.
In case you already have Hugo installed, feel free to use it with the `make serve` target.

Add Dockerfile and .dockerignore with targets in Makefile

---

content/en/docs/howto/chart_releaser_action.md
content/es/docs/howto/chart_releaser_action.md
content/uk/docs/howto/chart_releaser_action.md
content/zh/docs/howto/chart_releaser_action.md

The PR replaces deprecated `helm delete` command with `helm uninstall` on the `chart_releaser_action.md` pages.

Replace deprecated "helm delete" with "helm uninstall"

---

content/en/docs/chart_template_guide/functions_and_pipelines.md

Hi :wave:,
Regarding `lookup` function, I discovered that this point needs to be explicitly written.

docs: add note about namespace-scoped resources

---

content/en/docs/topics/plugins.md
content/ko/docs/topics/plugins.md
content/uk/docs/topics/plugins.md

The flag parsing section of the plugins guide does not contain an up-to-date list of global helm args.
```
--burst-limit int               missing in documentation and currently passed to plugins
--kube-apiserver string    missing in documentation
--kube-as-group stringArray    missing in documentation
--kube-as-user string             missing in documentation
--kube-ca-file string             missing in documentation
--kube-insecure-skip-tls-verify   missing in documentation
--kube-tls-server-name string     missing in documentation
--kube-token string              missing in documentation
--qps float32                    missing in documentation and currently passed to plugins
```
First, this PR re-orders the flags so that they appear in alphabetical order - the same order as `helm …

Update args that will be consumed by the root helm command

---

content/en/docs/intro/CheatSheet.md

fix: typo in CheatSheet.md

---

content/en/docs/sdk/examples.md
content/uk/docs/sdk/examples.md

Current link is [broken](https://github.com/helm/helm-www/sdkexamples).

Fix broken links for sdk examples source

---

.github/workflows/build.yml
.gitignore
Makefile
sdkexamples/Makefile

Add a build test for sdkexamples

chore: Add build workflow for sdkexamples

---

content/ko/docs/howto/charts_tips_and_tricks.md

Signed-off-by: Donghyeok Jang (jdhyeok97@gmail.com)
Translate a few docs to Korean

[Kr] Translate char_tips docs to Korean

---

content/en/docs/community/related.md
content/ko/docs/community/related.md
content/uk/docs/community/related.md
content/zh/docs/community/related.md

Removes traces of archived plugin:
- `helm-schema-gen`
Change url of plugin:
- `helm-unittest`
---
resolves #1723

chore: remove archived and update plugin link

---

content/ko/docs/community/release_checklist.md

- Replace “spring” with “sprig” in the korean docs

Fix typo in the korean docs

---

content/en/docs/topics/registries.md

RepoFlow supports hosting private Helm registries using the OCI standard, similar to other tools listed.
Signed-off-by: Tomer Cohen <100tomer@gmail.com>

Add RepoFlow to list of supported private Helm registries

---

content/en/docs/chart_template_guide/function_list.md

Updates the documentation adding a section for toYaml and toYamlPretty
Adds documentation which was noted missing from https://github.com/helm/helm/issues/30790

[docs] - toYaml / toYamlPretty

---

content/en/blog/2019-04-18-helm-summit-eu-2019.md
content/en/blog/2019-06-10-get-helm-sh.md
content/en/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
content/en/blog/2020-10-30-charts-repo-deprecation.md
content/en/blog/2022-02-28-storing-charts-in-oci.md
content/en/blog/helm-at-kubecon-eu-25.md
content/en/docs/community/related.md
content/en/docs/sdk/examples.md
content/en/docs/topics/kubernetes_distros.md
content/en/docs/topics/plugins.md

Used the [`typos` CLI](https://github.com/crate-ci/typos) to prepare this PR. I ran:
```bash
typos -w ./content/en
```
and then removed some false positives manually.

Fix all the typos with help of `typos` CLI
